[project]

dependencies = [
  "deprecated>=1.2.13",
  "numpy>=1.21.2",
  "pandas>=1.5.0",
  "scipy>=1.9.1",
]

[project.optional-dependencies]
test = [
  "pytest>=8.3.3",
  "pytest-cov>=5.0.0",
  "pytest-mock>=3.14.0",
  "pytest-snapshot>=0.9.0",
  "ruff>=0.7.0",
  "pre-commit>=2.7.1",
  "bump2version>=1.0.1",
  "pytest-benchmark>=3.4.1",
]

deploy = [
    "flit==3.4.0",
]


[tool.ruff]
line-length = 120