# -*- coding: utf-8 -*-
# snapshottest: v1 - https://goo.gl/zC4yUc
from __future__ import unicode_literals

from snapshottest import Snapshot


snapshots = Snapshot()

snapshots['test_config_loader Config'] = {
    'Land_Cover': {
        'LAI': None,
        'LAI_distribution_method': 'fraction',
        'LAI_method': 'carbon',
        'SAI': 4.28571414947509,
        'SAI_method': 'constant',
        'dvi_method': 'JULES',
        'fLAI': [
            [
                1.0
            ]
        ],
        'height_method': 'carbon',
        'land_cover_type': 'CROP',
        'layer_height_frac': [
            1.0
        ],
        'leaf_emergence_multiplier': 1,
        'max_lai_per_layer': None,
        'nL': 1,
        'nLC': 1,
        'nP': 1,
        'ozone_deposition_method': 'single layer',
        'parameters': [
            {
                'Lm': 0.02,
                'PID': 40,
                'Y': 6.0,
                'cosA': 0.5,
                'gsto': {
                    'SWP_max': -0.05,
                    'SWP_min': -1.25,
                    'Tleaf_method': 'ambient',
                    'VPD_crit': 8.0,
                    'VPD_max': 1.2,
                    'VPD_min': 3.2,
                    'fSWP_exp_a': 0.355,
                    'fSWP_exp_b': -0.706,
                    'fSWP_exp_curve': 'temperate',
                    'f_SW_method': 'disabled',
                    'f_VPD_method': 'linear',
                    'fmin': 0.01,
                    'method': 'photosynthesis'
                },
                'height': 1.0,
                'multip_gsto': {
                    'T_max': None,
                    'T_min': None,
                    'T_opt': None,
                    'f_O3_method': 'disabled',
                    'f_light_method': 'disabled',
                    'f_lightfac': 0.006,
                    'f_temp_method': 'disabled',
                    'gmax': None,
                    'gmorph': 1.0
                },
                'name': 'Spanish Wheat',
                'phenology': {
                    'LAI_1': None,
                    'LAI_2': None,
                    'LAI_a': None,
                    'LAI_b': None,
                    'LAI_c': None,
                    'LAI_d': None,
                    'PIV': 1.5,
                    'PRESET': 'WHEAT_SPRING',
                    'SAI_method': 'wheat',
                    'day_fphen_plf': {
                        'f_phen_1': None,
                        'f_phen_2': None,
                        'f_phen_3': None,
                        'f_phen_4': None,
                        'f_phen_a': None,
                        'f_phen_b': None,
                        'f_phen_c': None,
                        'f_phen_d': None,
                        'f_phen_e': None,
                        'f_phen_limA': None,
                        'f_phen_limB': None,
                        'leaf_f_phen_1': None,
                        'leaf_f_phen_2': None,
                        'leaf_f_phen_a': None,
                        'leaf_f_phen_b': None,
                        'leaf_f_phen_c': None
                    },
                    'dvi_interval': None,
                    'f_Astart': None,
                    'f_fphen_1_ets': None,
                    'f_fphen_3_ets': None,
                    'f_fphen_4_ets': None,
                    'f_fphen_5_ets': None,
                    'f_fphen_a': None,
                    'f_fphen_b': None,
                    'f_fphen_c': None,
                    'f_fphen_d': None,
                    'f_leaf_f_fphen': None,
                    'f_mid_anthesis': None,
                    'f_phen_method': 'disabled',
                    'f_phen_min': None,
                    'f_t_lem': None,
                    'f_t_lep': None,
                    'f_t_lma': None,
                    'f_t_lse': None,
                    'f_t_lse_mature': None,
                    'f_tt_emr': None,
                    'f_tt_rep': None,
                    'f_tt_veg': None,
                    'fphen_intervals': None,
                    'key_dates': {
                        'Aend': 208,
                        'Astart': 81,
                        'emergence': 112,
                        'harvest': None,
                        'mid_anthesis': None,
                        'sowing': 79
                    },
                    'key_dates_td': {
                        'Aend': None,
                        'Astart': None,
                        'emergence': 0,
                        'harvest': None,
                        'mid_anthesis': None,
                        'sowing': None
                    },
                    'key_lengths': {
                        'emerg_to_astart': None,
                        'emerg_to_end': None,
                        'emerg_to_veg': None,
                        'sowing_to_astart': None,
                        'sowing_to_emerge': None,
                        'sowing_to_end': None,
                        'sowing_to_f_phen_b': None,
                        'sowing_to_f_phen_c': None,
                        'veg_to_harvest': None
                    },
                    'key_lengths_flag_leaf': {
                        'leaf_f_phen_e': None,
                        'leaf_f_phen_g': None,
                        'leaf_f_phen_h': None,
                        'leaf_f_phen_i': None,
                        'plant_emerg_to_leaf_emerg': None,
                        'tl': None,
                        'tl_em': None,
                        'tl_ep': None,
                        'tl_ma': None,
                        'tl_se': None
                    },
                    'key_lengths_flag_leaf_td': {
                        'leaf_f_phen_e': None,
                        'leaf_f_phen_g': None,
                        'leaf_f_phen_h': None,
                        'leaf_f_phen_i': None,
                        'plant_emerg_to_leaf_emerg': None,
                        'tl': None,
                        'tl_em': None,
                        'tl_ep': None,
                        'tl_ma': None,
                        'tl_se': None
                    },
                    'key_lengths_leaf': {
                        'leaf_f_phen_e': None,
                        'leaf_f_phen_g': None,
                        'leaf_f_phen_h': None,
                        'leaf_f_phen_i': None,
                        'plant_emerg_to_leaf_emerg': None,
                        'tl': None,
                        'tl_em': None,
                        'tl_ep': None,
                        'tl_ma': None,
                        'tl_se': None
                    },
                    'key_lengths_leaf_td': {
                        'leaf_f_phen_e': None,
                        'leaf_f_phen_g': None,
                        'leaf_f_phen_h': None,
                        'leaf_f_phen_i': None,
                        'plant_emerg_to_leaf_emerg': None,
                        'tl': 2200,
                        'tl_em': 1000,
                        'tl_ep': 800,
                        'tl_ma': 1200,
                        'tl_se': 400
                    },
                    'key_lengths_td': {
                        'emerg_to_astart': None,
                        'emerg_to_end': None,
                        'emerg_to_veg': None,
                        'sowing_to_astart': None,
                        'sowing_to_emerge': None,
                        'sowing_to_end': 2200,
                        'sowing_to_f_phen_b': None,
                        'sowing_to_f_phen_c': None,
                        'veg_to_harvest': None
                    },
                    'leaf_f_phen_a': None,
                    'leaf_f_phen_b': None,
                    'leaf_f_phen_method': 'disabled',
                    'leaf_fphen_intervals': None,
                    'v_T_max': 30,
                    'v_T_min': 15
                },
                'pn_gsto': {
                    'D_0': 0.75,
                    'D_0_method': 'constant',
                    'F_0': 37,
                    'J_max_25': 400.0,
                    'K_z': 24,
                    'R_d_coeff': 0.015,
                    'Tleaf_adjustment_factor': 0.02,
                    'Tleaf_balance_threshold': 0.001,
                    'Tleaf_max_iterations': 50,
                    'V_J_method': 'constant',
                    'V_cmax_25': 180.0,
                    'g_sto_0': 20000.0,
                    'gamma_1': 0.06,
                    'gamma_2': 0.0045,
                    'gamma_3': 0.5,
                    'gamma_4_senes': 1,
                    'gamma_5_harvest': 0,
                    'leaf_f_phen_Anet_influence': 'disabled',
                    'm': 8.12,
                    'p_crit': 24,
                    'p_sens': 0,
                    'senescence_method': 'ewert',
                    't_b': 0,
                    't_m': 30,
                    't_o': 20,
                    'tt_emr': None,
                    'tt_rep': None,
                    'tt_veg': None,
                    'use_O3_damage': True
                }
            }
        ],
        'phenology_options': {
            'LAI_method': 'estimate total',
            'dvi_method': 'disabled',
            'flag_leaf_emerge_method': 'constant',
            'flag_leaf_only': False,
            'latitude': None,
            'phenology_method': 'season_fraction',
            'phenology_method_flag_leaf': 'same as canopy',
            'plant_emerge_method': 'constant',
            'sgs_key_day': 'sowing_day',
            'sgs_time_type': 'julian_day',
            'sowing_day_method': 'INPUT',
            'time_type': 'thermal_time',
            'use_photoperiod_factor': False,
            'use_vernalisation': False,
            'zero_day': 'sowing'
        },
        'primary_LC': 0
    },
    'Location': {
        'O3_d': None,
        'O3_z0': None,
        'OTC': False,
        'Rsoil': 200,
        'albedo': 0.2,
        'elev': 20.0,
        'end_day': None,
        'h_O3': None,
        'h_u': None,
        'izr': 50,
        'land_cover_type': 'CROP',
        'lat': 40.43,
        'lon': -3.7,
        'start_day': None,
        'u_d': None,
        'u_z0': None,
        'z_O3': 50.0,
        'z_u': 10.0,
        'zero_year': None
    },
    'Met': {
        'PARsunshade_method': 'FARQUHAR1997',
        'inputs': {
            'CO2_constant': 391.0,
            'CO2_method': 'constant',
            'Hd_constant': None,
            'Hd_method': 'skip',
            'Idfuse_constant': None,
            'Idfuse_method': 'calculated',
            'Idrctt_constant': None,
            'Idrctt_method': 'calculated',
            'J_max_25_constant': None,
            'J_max_25_method': 'skip',
            'LAI_constant': None,
            'LAI_method': 'input',
            'O3_constant': None,
            'O3_method': 'input',
            'O3_nmol_constant': None,
            'O3_nmol_method': 'calculated',
            'PAR_constant': None,
            'PAR_method': 'input',
            'PPFD_constant': None,
            'PPFD_method': 'calculated',
            'P_constant': None,
            'P_method': 'input',
            'RH_constant': None,
            'RH_method': 'calculated',
            'R_constant': None,
            'R_method': 'calculated',
            'Rn_constant': None,
            'Rn_method': 'calculated',
            'SWC_constant': None,
            'SWC_method': 'skip',
            'SWP_constant': None,
            'SWP_method': 'skip',
            'Tleaf_C_constant': None,
            'Tleaf_C_method': 'skip',
            'Ts_C_constant': None,
            'Ts_C_method': 'input',
            'Ts_K_constant': None,
            'Ts_K_method': 'skip',
            'VPD_constant': None,
            'VPD_dd_constant': None,
            'VPD_dd_method': 'calculated',
            'VPD_method': 'input',
            'V_cmax_25_constant': None,
            'V_cmax_25_method': 'skip',
            'cloudfrac_constant': None,
            'cloudfrac_method': 'skip',
            'date_method': 'skip',
            'dd_method': 'input',
            'eact_constant': None,
            'eact_method': 'calculated',
            'esat_constant': None,
            'esat_method': 'calculated',
            'fphen_constant': None,
            'fphen_method': 'skip',
            'h_constant': None,
            'h_method': 'skip',
            'hr_method': 'input',
            'is_daylight_constant': None,
            'is_daylight_method': 'calculated',
            'leaf_fphen_constant': None,
            'leaf_fphen_method': 'skip',
            'precip_constant': None,
            'precip_method': 'input',
            'sinB_constant': None,
            'sinB_method': 'calculated',
            'snow_depth_constant': None,
            'snow_depth_method': 'skip',
            'td_constant': None,
            'td_method': 'calculated',
            'u__constant': None,
            'u__method': 'skip',
            'u_constant': None,
            'u_method': 'input',
            'uh_constant': None,
            'uh_method': 'skip',
            'ustar_constant': None,
            'ustar_method': 'skip',
            'ustar_ref_constant': None,
            'ustar_ref_method': 'skip'
        },
        'td_base_temperature': 0,
        'thermal_time_method': 'EXTERNAL',
        'thermal_time_offset': 0,
        'thermal_time_start': 0
    },
    'VERSION': 10,
    'carbon_allocation': {
        'a_leaf': 18.0,
        'a_root': 18.5,
        'a_stem': 16.0,
        'b_leaf': -18.5,
        'b_root': -20.0,
        'b_stem': -15.0,
        'delta': -0.0507,
        'gamma': 27.3,
        'k': 1.4,
        'lambdav': 0.4,
        'theta': 0.4,
        'use_carbon_allocation': True
    },
    'output': {
        'fields': [
            'dd',
            'hr',
            'ts_c',
            'par',
            'td',
            'td_v',
            'photoperiod_factor',
            'Vf',
            'V_acc',
            'V_tot',
            'lai',
            'sai',
            'dvi',
            'photoperiod',
            'o3_ppb_i',
            'u_i',
            'Tleaf_C',
            'ustar',
            'canopy_height',
            'micro_u',
            'micro_O3',
            'PARsun',
            'PARshade',
            'o3_ppb',
            'o3_nmol_m3',
            'layer_height',
            'LAI_flag',
            'A_n',
            'A_n_limit_factor',
            'fst',
            'fst_canopy',
            'fst_acc',
            'fst_acc_day',
            'fst_acc_day_prev',
            'rsto_l',
            'rb_l',
            'gsto_l',
            'gsto_l_bulk',
            'gsto',
            'gsto_bulk',
            'gsto_canopy',
            'A_n_canopy',
            'c_root',
            'c_stem',
            'c_leaf',
            'c_harv',
            'c_resv',
            'npp',
            'npp_acc',
            'fO3_h',
            'fO3_d',
            'fO3_l',
            'f_LS',
            'f_LA',
            'c_i',
            'td_dd',
            'td_dd_flag',
            'pody',
            'pod0',
            'precip_acc',
            'swp',
            'asw',
            'smd',
            'sn',
            'ei',
            'et',
            'pet',
            'es',
            'ei_acc',
            'et_acc',
            'pet_acc',
            'es_acc',
            'f_phen',
            'leaf_f_phen',
            'f_light',
            'leaf_f_light',
            'f_temp',
            'f_VPD',
            'f_SW',
            'f_O3',
            'rsto_c',
            'ra',
            'rb',
            'rsur',
            'rinc',
            'V_cmax_25',
            'J_max_25',
            'LAIsunfrac',
            'component_LAI',
            'V_cmax',
            'J_max',
            'R_d',
            'R_dc',
            'total_emerged_leaves',
            'leaf_phenology_stage',
            'leaf_pop_distribution',
            'phenology_stage',
            'growing_populations',
            'layer_lai',
            'fLAI'
        ],
        'log_multilayer': False
    },
    'resistance': {
        'ra_calc_method': 'simple',
        'rext_calc_method': 'const',
        'rsur_calc_method': 'single_layer'
    },
    'soil_moisture': {
        'ASW_FC': None,
        'MAD': 0.0,
        'PWP': -4.0,
        'initial_SWC': None,
        'root': 0.75,
        'run_off_fraction': 0.0,
        'soil_config': {
            'FC': None,
            'Ksat': None,
            'SWP_AE': None,
            'b': None
        },
        'soil_texture': 'loam',
        'source': 'P-M'
    }
}

snapshots['test_json_to_config Config from json'] = {
    'Land_Cover': {
        'LAI': None,
        'LAI_distribution_method': 'fraction',
        'LAI_method': 'estimate total',
        'SAI': None,
        'SAI_method': 'estimate total',
        'dvi_method': 'disabled',
        'fLAI': [
            [
                1.0
            ]
        ],
        'height_method': 'constant',
        'land_cover_type': 'CROP',
        'layer_height_frac': [
            1.0
        ],
        'leaf_emergence_multiplier': 1,
        'max_lai_per_layer': None,
        'nL': 1,
        'nLC': 1,
        'nP': 1,
        'ozone_deposition_method': 'single layer',
        'parameters': [
            {
                'Lm': None,
                'PID': 40,
                'Y': 0,
                'cosA': 0.5,
                'gsto': {
                    'SWP_max': None,
                    'SWP_min': None,
                    'Tleaf_method': 'ambient',
                    'VPD_crit': 1000.0,
                    'VPD_max': None,
                    'VPD_min': None,
                    'fSWP_exp_a': None,
                    'fSWP_exp_b': None,
                    'fSWP_exp_curve': 'temperate',
                    'f_SW_method': 'disabled',
                    'f_VPD_method': 'disabled',
                    'fmin': None,
                    'method': 'photosynthesis'
                },
                'height': None,
                'multip_gsto': {
                    'T_max': None,
                    'T_min': None,
                    'T_opt': None,
                    'f_O3_method': 'disabled',
                    'f_light_method': 'disabled',
                    'f_lightfac': 0.006,
                    'f_temp_method': 'disabled',
                    'gmax': None,
                    'gmorph': 1.0
                },
                'name': 'p01',
                'phenology': {
                    'LAI_1': None,
                    'LAI_2': None,
                    'LAI_a': None,
                    'LAI_b': None,
                    'LAI_c': None,
                    'LAI_d': None,
                    'PIV': 1.5,
                    'PRESET': None,
                    'SAI_method': 'LAI',
                    'day_fphen_plf': {
                        'f_phen_1': None,
                        'f_phen_2': None,
                        'f_phen_3': None,
                        'f_phen_4': None,
                        'f_phen_a': None,
                        'f_phen_b': None,
                        'f_phen_c': None,
                        'f_phen_d': None,
                        'f_phen_e': None,
                        'f_phen_limA': None,
                        'f_phen_limB': None,
                        'leaf_f_phen_1': None,
                        'leaf_f_phen_2': None,
                        'leaf_f_phen_a': None,
                        'leaf_f_phen_b': None,
                        'leaf_f_phen_c': None
                    },
                    'dvi_interval': None,
                    'f_Astart': None,
                    'f_fphen_1_ets': None,
                    'f_fphen_3_ets': None,
                    'f_fphen_4_ets': None,
                    'f_fphen_5_ets': None,
                    'f_fphen_a': None,
                    'f_fphen_b': None,
                    'f_fphen_c': None,
                    'f_fphen_d': None,
                    'f_leaf_f_fphen': None,
                    'f_mid_anthesis': None,
                    'f_phen_method': 'disabled',
                    'f_phen_min': None,
                    'f_t_lem': None,
                    'f_t_lep': None,
                    'f_t_lma': None,
                    'f_t_lse': None,
                    'f_t_lse_mature': None,
                    'f_tt_emr': None,
                    'f_tt_rep': None,
                    'f_tt_veg': None,
                    'fphen_intervals': None,
                    'key_dates': {
                        'Aend': None,
                        'Astart': None,
                        'emergence': None,
                        'harvest': None,
                        'mid_anthesis': None,
                        'sowing': None
                    },
                    'key_dates_td': {
                        'Aend': None,
                        'Astart': None,
                        'emergence': None,
                        'harvest': None,
                        'mid_anthesis': None,
                        'sowing': None
                    },
                    'key_lengths': {
                        'emerg_to_astart': None,
                        'emerg_to_end': None,
                        'emerg_to_veg': None,
                        'sowing_to_astart': None,
                        'sowing_to_emerge': None,
                        'sowing_to_end': None,
                        'sowing_to_f_phen_b': None,
                        'sowing_to_f_phen_c': None,
                        'veg_to_harvest': None
                    },
                    'key_lengths_flag_leaf': {
                        'leaf_f_phen_e': None,
                        'leaf_f_phen_g': None,
                        'leaf_f_phen_h': None,
                        'leaf_f_phen_i': None,
                        'plant_emerg_to_leaf_emerg': None,
                        'tl': None,
                        'tl_em': None,
                        'tl_ep': None,
                        'tl_ma': None,
                        'tl_se': None
                    },
                    'key_lengths_flag_leaf_td': {
                        'leaf_f_phen_e': None,
                        'leaf_f_phen_g': None,
                        'leaf_f_phen_h': None,
                        'leaf_f_phen_i': None,
                        'plant_emerg_to_leaf_emerg': None,
                        'tl': None,
                        'tl_em': None,
                        'tl_ep': None,
                        'tl_ma': None,
                        'tl_se': None
                    },
                    'key_lengths_leaf': {
                        'leaf_f_phen_e': None,
                        'leaf_f_phen_g': None,
                        'leaf_f_phen_h': None,
                        'leaf_f_phen_i': None,
                        'plant_emerg_to_leaf_emerg': None,
                        'tl': None,
                        'tl_em': None,
                        'tl_ep': None,
                        'tl_ma': None,
                        'tl_se': None
                    },
                    'key_lengths_leaf_td': {
                        'leaf_f_phen_e': None,
                        'leaf_f_phen_g': None,
                        'leaf_f_phen_h': None,
                        'leaf_f_phen_i': None,
                        'plant_emerg_to_leaf_emerg': None,
                        'tl': None,
                        'tl_em': None,
                        'tl_ep': None,
                        'tl_ma': None,
                        'tl_se': None
                    },
                    'key_lengths_td': {
                        'emerg_to_astart': None,
                        'emerg_to_end': None,
                        'emerg_to_veg': None,
                        'sowing_to_astart': None,
                        'sowing_to_emerge': None,
                        'sowing_to_end': None,
                        'sowing_to_f_phen_b': None,
                        'sowing_to_f_phen_c': None,
                        'veg_to_harvest': None
                    },
                    'leaf_f_phen_a': None,
                    'leaf_f_phen_b': None,
                    'leaf_f_phen_method': 'disabled',
                    'leaf_fphen_intervals': None,
                    'v_T_max': 30,
                    'v_T_min': 15
                },
                'pn_gsto': {
                    'D_0': None,
                    'D_0_method': 'f_VPD',
                    'F_0': 1.0,
                    'J_max_25': None,
                    'K_z': 24.0,
                    'R_d_coeff': None,
                    'Tleaf_adjustment_factor': 0.02,
                    'Tleaf_balance_threshold': 0.001,
                    'Tleaf_max_iterations': 50,
                    'V_J_method': 'constant',
                    'V_cmax_25': None,
                    'g_sto_0': None,
                    'gamma_1': 0.06,
                    'gamma_2': 0.0045,
                    'gamma_3': 0.5,
                    'gamma_4_senes': 1,
                    'gamma_5_harvest': 0,
                    'leaf_f_phen_Anet_influence': 'disabled',
                    'm': None,
                    'p_crit': 24,
                    'p_sens': 0,
                    'senescence_method': 'ewert',
                    't_b': 0,
                    't_m': 30,
                    't_o': 20,
                    'tt_emr': None,
                    'tt_rep': None,
                    'tt_veg': None,
                    'use_O3_damage': True
                }
            }
        ],
        'phenology_options': {
            'LAI_method': 'estimate total',
            'dvi_method': 'disabled',
            'flag_leaf_emerge_method': 'constant',
            'flag_leaf_only': False,
            'latitude': None,
            'phenology_method': None,
            'phenology_method_flag_leaf': 'same as canopy',
            'plant_emerge_method': 'constant',
            'sgs_key_day': 'sowing_day',
            'sgs_time_type': 'julian_day',
            'sowing_day_method': 'INPUT',
            'time_type': 'thermal_time',
            'use_photoperiod_factor': False,
            'use_vernalisation': False,
            'zero_day': 'sowing'
        },
        'primary_LC': 0
    },
    'Location': {
        'O3_d': None,
        'O3_z0': None,
        'OTC': False,
        'Rsoil': 100,
        'albedo': None,
        'elev': None,
        'end_day': None,
        'h_O3': None,
        'h_u': None,
        'izr': 50,
        'land_cover_type': 'CROP',
        'lat': 40.43,
        'lon': -3.7,
        'start_day': None,
        'u_d': None,
        'u_z0': None,
        'z_O3': None,
        'z_u': None,
        'zero_year': None
    },
    'Met': {
        'PARsunshade_method': 'FARQUHAR1997',
        'inputs': {
            'CO2_constant': 391.0,
            'CO2_method': 'constant',
            'Hd_constant': None,
            'Hd_method': 'skip',
            'Idfuse_constant': None,
            'Idfuse_method': 'calculated',
            'Idrctt_constant': None,
            'Idrctt_method': 'calculated',
            'J_max_25_constant': None,
            'J_max_25_method': 'skip',
            'LAI_constant': None,
            'LAI_method': 'skip',
            'O3_constant': None,
            'O3_method': 'input',
            'O3_nmol_constant': None,
            'O3_nmol_method': 'calculated',
            'PAR_constant': None,
            'PAR_method': 'input',
            'PPFD_constant': None,
            'PPFD_method': 'calculated',
            'P_constant': None,
            'P_method': 'input',
            'RH_constant': None,
            'RH_method': 'calculated',
            'R_constant': None,
            'R_method': 'calculated',
            'Rn_constant': None,
            'Rn_method': 'calculated',
            'SWC_constant': None,
            'SWC_method': 'skip',
            'SWP_constant': None,
            'SWP_method': 'skip',
            'Tleaf_C_constant': None,
            'Tleaf_C_method': 'skip',
            'Ts_C_constant': None,
            'Ts_C_method': 'input',
            'Ts_K_constant': None,
            'Ts_K_method': 'skip',
            'VPD_constant': None,
            'VPD_dd_constant': None,
            'VPD_dd_method': 'calculated',
            'VPD_method': 'input',
            'V_cmax_25_constant': None,
            'V_cmax_25_method': 'skip',
            'cloudfrac_constant': None,
            'cloudfrac_method': 'skip',
            'date_method': 'skip',
            'dd_method': 'input',
            'eact_constant': None,
            'eact_method': 'calculated',
            'esat_constant': None,
            'esat_method': 'calculated',
            'fphen_constant': None,
            'fphen_method': 'skip',
            'h_constant': None,
            'h_method': 'skip',
            'hr_method': 'input',
            'is_daylight_constant': None,
            'is_daylight_method': 'calculated',
            'leaf_fphen_constant': None,
            'leaf_fphen_method': 'skip',
            'precip_constant': None,
            'precip_method': 'input',
            'sinB_constant': None,
            'sinB_method': 'calculated',
            'snow_depth_constant': None,
            'snow_depth_method': 'skip',
            'td_constant': None,
            'td_method': 'calculated',
            'u__constant': None,
            'u__method': 'skip',
            'u_constant': None,
            'u_method': 'input',
            'uh_constant': None,
            'uh_method': 'skip',
            'ustar_constant': None,
            'ustar_method': 'skip',
            'ustar_ref_constant': None,
            'ustar_ref_method': 'skip'
        },
        'td_base_temperature': 0.0,
        'thermal_time_method': 'EXTERNAL',
        'thermal_time_offset': 0,
        'thermal_time_start': 0
    },
    'VERSION': None,
    'carbon_allocation': {
        'a_leaf': None,
        'a_root': None,
        'a_stem': None,
        'b_leaf': None,
        'b_root': None,
        'b_stem': None,
        'delta': None,
        'gamma': None,
        'k': None,
        'lambdav': None,
        'theta': None,
        'use_carbon_allocation': False
    },
    'output': {
        'fields': [
            'dd',
            'hr',
            'ts_c',
            'par',
            'td',
            'td_v',
            'photoperiod_factor',
            'Vf',
            'V_acc',
            'V_tot',
            'lai',
            'sai',
            'dvi',
            'photoperiod',
            'o3_ppb_i',
            'u_i',
            'Tleaf_C',
            'ustar',
            'canopy_height',
            'micro_u',
            'micro_O3',
            'PARsun',
            'PARshade',
            'o3_ppb',
            'o3_nmol_m3',
            'layer_height',
            'LAI_flag',
            'A_n',
            'A_n_limit_factor',
            'fst',
            'fst_canopy',
            'fst_acc',
            'fst_acc_day',
            'fst_acc_day_prev',
            'rsto_l',
            'rb_l',
            'gsto_l',
            'gsto_l_bulk',
            'gsto',
            'gsto_bulk',
            'gsto_canopy',
            'A_n_canopy',
            'c_root',
            'c_stem',
            'c_leaf',
            'c_harv',
            'c_resv',
            'npp',
            'npp_acc',
            'fO3_h',
            'fO3_d',
            'fO3_l',
            'f_LS',
            'f_LA',
            'c_i',
            'td_dd',
            'td_dd_flag',
            'pody',
            'pod0',
            'precip_acc',
            'swp',
            'asw',
            'smd',
            'sn',
            'ei',
            'et',
            'pet',
            'es',
            'ei_acc',
            'et_acc',
            'pet_acc',
            'es_acc',
            'f_phen',
            'leaf_f_phen',
            'f_light',
            'leaf_f_light',
            'f_temp',
            'f_VPD',
            'f_SW',
            'f_O3',
            'rsto_c',
            'ra',
            'rb',
            'rsur',
            'rinc',
            'V_cmax_25',
            'J_max_25',
            'LAIsunfrac',
            'component_LAI',
            'V_cmax',
            'J_max',
            'R_d',
            'R_dc',
            'total_emerged_leaves',
            'leaf_phenology_stage',
            'leaf_pop_distribution',
            'phenology_stage',
            'growing_populations',
            'layer_lai',
            'fLAI'
        ],
        'log_multilayer': False
    },
    'resistance': {
        'ra_calc_method': 'simple',
        'rext_calc_method': 'const',
        'rsur_calc_method': 'single_layer'
    },
    'soil_moisture': {
        'ASW_FC': None,
        'MAD': 0.0,
        'PWP': -4.0,
        'initial_SWC': None,
        'root': 1.2,
        'run_off_fraction': 0.0,
        'soil_config': {
            'FC': None,
            'Ksat': None,
            'SWP_AE': None,
            'b': None
        },
        'soil_texture': 'loam',
        'source': 'disabled'
    }
}
