# -*- coding: utf-8 -*-
# snapshottest: v1 - https://goo.gl/zC4yUc
from __future__ import unicode_literals

from snapshottest import GenericRepr, Snapshot


snapshots = Snapshot()

snapshots['test_config_init_processes proccesses'] = [
    GenericRepr('Process(func=process_phenology_config; ptype=ProcessType.STANDARD; comment="Estimate key phenology dates from input config and data."; gate=True; group=None; config_inputs={}; parameters_inputs={}; external_state_inputs={\'e_state and asdict(e_state\': None}; additional_inputs={}; state_inputs={\'state.Land_Cover.nP\': \'"nP"\', \'state.Land_Cover.phenology_options\': \'"model_config"\', \'state.Land_Cover.parameters.[iLC].phenology\': \'"species_config"\', \'state.Met.td_base_temperature\': \'td_base_temperature\'}; state_outputs={\'result.0\': \'state.Land_Cover.phenology_options\', \'result.1\': "state.f\'Land_Cover.parameters.{iLC}.phenology"}; args=[])'),
    GenericRepr('Process(func=get_thermal_time_base_and_offset; ptype=ProcessType.STANDARD; comment="Set td start and offset"; gate=True; group=None; config_inputs={}; parameters_inputs={}; external_state_inputs={}; additional_inputs={}; state_inputs={\'state.Land_Cover.phenology_options.zero_day\': \'"zero_day"\', \'state.Land_Cover.parameters.0.phenology.key_dates.sowing\': \'sowing_day\', \'state.Land_Cover.parameters.0.phenology.key_dates.Astart\': \'Astart_day\'}; state_outputs={\'result.0\': \'state.Met.thermal_time_start\', \'result.1\': \'state.Met.thermal_time_offset\'}; args=[])'),
    GenericRepr('Process(func=get_soil_config; ptype=ProcessType.STANDARD; comment="Check that a Soil_t is valid"; gate=True; group=None; config_inputs={}; parameters_inputs={}; external_state_inputs={}; additional_inputs={}; state_inputs={\'state.soil_moisture.soil_texture\': \'name\', \'state.soil_moisture.soil_config\': \'soil_in\'}; state_outputs={\'result\': \'state.soil_moisture.soil_config\'}; args=[])'),
    GenericRepr('Process(func=calc_ASW; ptype=ProcessType.STANDARD; comment="Calculate available soil water at field capacity"; gate=True; group=None; config_inputs={}; parameters_inputs={}; external_state_inputs={}; additional_inputs={}; state_inputs={\'state.soil_moisture.soil_config\': \'soil_config\', \'state.soil_moisture.PWP\': \'PWP\', \'state.soil_moisture.root\': \'root_depth\'}; state_outputs={\'result\': \'state.soil_moisture.ASW_FC\'}; args=[])'),
    GenericRepr('Process(func=get_initial_SWC; ptype=ProcessType.STANDARD; comment="Set up soil water data source parameters"; gate=True; group=None; config_inputs={}; parameters_inputs={}; external_state_inputs={}; additional_inputs={}; state_inputs={\'state.soil_moisture.initial_SWC\': \'SWC_in\', \'state.soil_moisture.soil_config.FC\': \'FC\'}; state_outputs={\'result\': \'state.soil_moisture.initial_SWC\'}; args=[])'),
    GenericRepr('Process(func=calc_displacement_and_roughness_parameters; ptype=ProcessType.STANDARD; comment="calculate measured wind canopy displacement parameters"; gate=True; group=None; config_inputs={}; parameters_inputs={}; external_state_inputs={}; additional_inputs={}; state_inputs={\'ERROR\': \'ERROR\'}; state_outputs={\'result.0\': \'state.Location.u_d\', \'result.1\': \'state.Location.u_z0\'}; args=[])'),
    GenericRepr('Process(func=calc_displacement_and_roughness_parameters; ptype=ProcessType.STANDARD; comment="calculate measured ozone canopy displacement parameters"; gate=True; group=None; config_inputs={}; parameters_inputs={}; external_state_inputs={}; additional_inputs={}; state_inputs={\'ERROR\': \'ERROR\'}; state_outputs={\'result.0\': \'state.Location.O3_d\', \'result.1\': \'state.Location.O3_z0\'}; args=[])')
]

snapshots['test_config_init_processes Process_comments'] = [
    'Estimate key phenology dates from input config and data.',
    'Set td start and offset',
    'Check that a Soil_t is valid',
    'Calculate available soil water at field capacity',
    'Set up soil water data source parameters',
    'calculate measured wind canopy displacement parameters',
    'calculate measured ozone canopy displacement parameters'
]

snapshots['test_config_init_processes config_amended'] = {
    'Land_Cover': {
        'LAI': None,
        'LAI_distribution_method': 'fraction',
        'LAI_method': 'carbon',
        'SAI': 4.28571414947509,
        'SAI_method': 'constant',
        'dvi_method': 'JULES',
        'fLAI': [
            [
                1.0
            ]
        ],
        'height_method': 'carbon',
        'land_cover_type': 'CROP',
        'layer_height_frac': [
            1.0
        ],
        'leaf_emergence_multiplier': 1,
        'max_lai_per_layer': None,
        'nL': 1,
        'nLC': 1,
        'nP': 1,
        'ozone_deposition_method': 'single layer',
        'parameters': [
            {
                'Lm': 0.02,
                'PID': 40,
                'Y': 6.0,
                'cosA': 0.5,
                'gsto': {
                    'SWP_max': -0.05,
                    'SWP_min': -1.25,
                    'Tleaf_method': 'ambient',
                    'VPD_crit': 8.0,
                    'VPD_max': 1.2,
                    'VPD_min': 3.2,
                    'fSWP_exp_a': 0.355,
                    'fSWP_exp_b': -0.706,
                    'fSWP_exp_curve': 'temperate',
                    'f_SW_method': 'disabled',
                    'f_VPD_method': 'linear',
                    'fmin': 0.01,
                    'method': 'photosynthesis'
                },
                'height': 1.0,
                'multip_gsto': {
                    'T_max': None,
                    'T_min': None,
                    'T_opt': None,
                    'f_O3_method': 'disabled',
                    'f_light_method': 'disabled',
                    'f_lightfac': 0.006,
                    'f_temp_method': 'disabled',
                    'gmax': None,
                    'gmorph': 1.0
                },
                'name': 'Spanish Wheat',
                'phenology': {
                    'LAI_1': None,
                    'LAI_2': None,
                    'LAI_a': None,
                    'LAI_b': None,
                    'LAI_c': None,
                    'LAI_d': None,
                    'PIV': 1.5,
                    'PRESET': 'WHEAT_SPRING',
                    'SAI_method': 'wheat',
                    'day_fphen_plf': {
                        'f_phen_1': None,
                        'f_phen_2': None,
                        'f_phen_3': None,
                        'f_phen_4': None,
                        'f_phen_a': None,
                        'f_phen_b': None,
                        'f_phen_c': None,
                        'f_phen_d': None,
                        'f_phen_e': None,
                        'f_phen_limA': None,
                        'f_phen_limB': None,
                        'leaf_f_phen_1': None,
                        'leaf_f_phen_2': None,
                        'leaf_f_phen_a': None,
                        'leaf_f_phen_b': None,
                        'leaf_f_phen_c': None
                    },
                    'dvi_interval': [
                        (
                            0,
                            -1.000000001
                        ),
                        (
                            110.0,
                            0.0
                        ),
                        (
                            946.0,
                            1.0
                        ),
                        (
                            2200.0,
                            2.0
                        )
                    ],
                    'f_Astart': 0.54,
                    'f_fphen_1_ets': 0.08,
                    'f_fphen_3_ets': 0.05,
                    'f_fphen_4_ets': 0.22,
                    'f_fphen_5_ets': 0.38,
                    'f_fphen_a': 0.05,
                    'f_fphen_b': 0.2,
                    'f_fphen_c': 0.62,
                    'f_fphen_d': 1.0,
                    'f_leaf_f_fphen': 0.46,
                    'f_mid_anthesis': 0.62,
                    'f_phen_method': 'disabled',
                    'f_phen_min': 0,
                    'f_t_lem': 0.14,
                    'f_t_lep': 0.31,
                    'f_t_lma': 0.46,
                    'f_t_lse': 0.15,
                    'f_t_lse_mature': 0.33,
                    'f_tt_emr': 0.05,
                    'f_tt_rep': 0.57,
                    'f_tt_veg': 0.38,
                    'fphen_intervals': [
                        (
                            0,
                            0
                        ),
                        (
                            110.0,
                            0
                        ),
                        (
                            440.0,
                            1
                        ),
                        (
                            1364.0,
                            1
                        ),
                        (
                            2200.0,
                            0
                        )
                    ],
                    'key_dates': {
                        'Aend': 208,
                        'Astart': 81,
                        'emergence': 112,
                        'harvest': None,
                        'mid_anthesis': None,
                        'sowing': 79
                    },
                    'key_dates_td': {
                        'Aend': 2200.0,
                        'Astart': 1188.0,
                        'emergence': 0,
                        'harvest': 2200.0,
                        'mid_anthesis': 1364.0,
                        'sowing': 0
                    },
                    'key_lengths': {
                        'emerg_to_astart': None,
                        'emerg_to_end': None,
                        'emerg_to_veg': None,
                        'sowing_to_astart': None,
                        'sowing_to_emerge': None,
                        'sowing_to_end': None,
                        'sowing_to_f_phen_b': None,
                        'sowing_to_f_phen_c': None,
                        'veg_to_harvest': None
                    },
                    'key_lengths_flag_leaf': {
                        'astart_to_senescence': None,
                        'leaf_emerg_to_astart': None,
                        'leaf_f_phen_e': None,
                        'leaf_f_phen_g': None,
                        'leaf_f_phen_h': None,
                        'leaf_f_phen_i': None,
                        'plant_emerg_to_leaf_emerg': None,
                        'tl': None,
                        'tl_em': None,
                        'tl_ep': None,
                        'tl_ma': None,
                        'tl_se': None
                    },
                    'key_lengths_flag_leaf_td': {
                        'astart_to_senescence': None,
                        'leaf_emerg_to_astart': None,
                        'leaf_f_phen_e': 176.0,
                        'leaf_f_phen_g': 110.0,
                        'leaf_f_phen_h': 484.0,
                        'leaf_f_phen_i': 836.0,
                        'plant_emerg_to_leaf_emerg': 770.0,
                        'tl': 1320.0,
                        'tl_em': 308.00000000000006,
                        'tl_ep': 682.0,
                        'tl_ma': 1012.0,
                        'tl_se': 330.0
                    },
                    'key_lengths_leaf': {
                        'astart_to_senescence': None,
                        'leaf_emerg_to_astart': None,
                        'leaf_f_phen_e': None,
                        'leaf_f_phen_g': None,
                        'leaf_f_phen_h': None,
                        'leaf_f_phen_i': None,
                        'plant_emerg_to_leaf_emerg': None,
                        'tl': None,
                        'tl_em': None,
                        'tl_ep': None,
                        'tl_ma': None,
                        'tl_se': None
                    },
                    'key_lengths_leaf_td': {
                        'astart_to_senescence': None,
                        'leaf_emerg_to_astart': None,
                        'leaf_f_phen_e': None,
                        'leaf_f_phen_g': None,
                        'leaf_f_phen_h': None,
                        'leaf_f_phen_i': None,
                        'plant_emerg_to_leaf_emerg': None,
                        'tl': 2200,
                        'tl_em': 1000,
                        'tl_ep': 800,
                        'tl_ma': 1200,
                        'tl_se': 400
                    },
                    'key_lengths_td': {
                        'emerg_to_astart': 1078.0,
                        'emerg_to_end': 2090.0,
                        'emerg_to_veg': 836.0,
                        'sowing_to_astart': 1188.0,
                        'sowing_to_emerge': 110.0,
                        'sowing_to_end': 2200,
                        'sowing_to_f_phen_b': 440.0,
                        'sowing_to_f_phen_c': 1364.0,
                        'veg_to_harvest': 1254.0
                    },
                    'leaf_f_phen_a': 0.3,
                    'leaf_f_phen_b': 0.7,
                    'leaf_f_phen_method': 'disabled',
                    'leaf_fphen_intervals': [
                        (
                            0,
                            0
                        ),
                        (
                            1188.0,
                            0
                        ),
                        (
                            1188.0,
                            1
                        ),
                        (
                            1364.0,
                            1
                        ),
                        (
                            1474.0,
                            1
                        ),
                        (
                            1848.0,
                            0.7
                        ),
                        (
                            2200.0,
                            0
                        ),
                        (
                            2200.0,
                            0
                        )
                    ],
                    'v_T_max': 30,
                    'v_T_min': 15
                },
                'pn_gsto': {
                    'D_0': 0.75,
                    'D_0_method': 'constant',
                    'F_0': 37,
                    'J_max_25': 400.0,
                    'K_z': 24,
                    'R_d_coeff': 0.015,
                    'Tleaf_adjustment_factor': 0.02,
                    'Tleaf_balance_threshold': 0.001,
                    'Tleaf_max_iterations': 50,
                    'V_J_method': 'constant',
                    'V_cmax_25': 180.0,
                    'V_cmax_25_kN': 0.78,
                    'cL3': 20000,
                    'g_sto_0': 20000.0,
                    'gamma_1': 0.06,
                    'gamma_2': 0.0045,
                    'gamma_3': 0.0005,
                    'gamma_4_senes': 1,
                    'gamma_5_harvest': 0,
                    'leaf_f_phen_Anet_influence': 'disabled',
                    'm': 8.12,
                    'p_crit': 24,
                    'p_sens': 0,
                    'senescence_method': 'ewert',
                    't_b': 0,
                    't_m': 30,
                    't_o': 20,
                    'tt_emr': None,
                    'tt_rep': None,
                    'tt_veg': None,
                    'use_O3_damage': True
                }
            }
        ],
        'phenology_options': {
            'LAI_method': 'estimate total',
            'dvi_method': 'disabled',
            'flag_leaf_emerge_method': 'constant',
            'flag_leaf_only': False,
            'latitude': None,
            'phenology_method': 'season_fraction',
            'phenology_method_flag_leaf': 'same as canopy',
            'plant_emerge_method': 'constant',
            'sgs_key_day': 'sowing_day',
            'sgs_time_type': 'julian_day',
            'sowing_day_method': 'INPUT',
            'time_type': 'thermal_time',
            'use_photoperiod_factor': False,
            'use_vernalisation': False,
            'zero_day': 'sowing'
        },
        'primary_LC': 0
    },
    'Location': {
        'O3_d': 35.0,
        'O3_z0': 5.0,
        'OTC': False,
        'Rsoil': 200,
        'albedo': 0.2,
        'elev': 20.0,
        'end_day': None,
        'h_O3': None,
        'h_u': None,
        'izr': 50,
        'land_cover_type': 'CROP',
        'lat': 40.43,
        'lon': -3.7,
        'multi_season': False,
        'multi_season_day': None,
        'start_day': None,
        'u_d': 7.0,
        'u_z0': 1.0,
        'z_O3': 50.0,
        'z_u': 10.0,
        'zero_year': None
    },
    'Met': {
        'PARsunshade_method': 'FARQUHAR1997',
        'dd_calc_method': None,
        'inputs': {
            'CO2_constant': 391.0,
            'CO2_fillna': None,
            'CO2_method': 'constant',
            'CO2_required': True,
            'Hd_constant': None,
            'Hd_fillna': None,
            'Hd_method': 'skip',
            'Hd_required': False,
            'Idfuse_constant': None,
            'Idfuse_fillna': None,
            'Idfuse_method': 'calculated',
            'Idfuse_required': False,
            'Idrctt_constant': None,
            'Idrctt_fillna': None,
            'Idrctt_method': 'calculated',
            'Idrctt_required': False,
            'J_max_25_constant': None,
            'J_max_25_fillna': None,
            'J_max_25_method': 'skip',
            'J_max_25_required': False,
            'LAI_constant': None,
            'LAI_fillna': None,
            'LAI_method': 'input',
            'LAI_required': False,
            'O3_constant': None,
            'O3_fillna': None,
            'O3_method': 'input',
            'O3_nmol_constant': None,
            'O3_nmol_fillna': None,
            'O3_nmol_method': 'calculated',
            'O3_nmol_required': False,
            'O3_required': True,
            'PAR_constant': None,
            'PAR_fillna': None,
            'PAR_method': 'input',
            'PAR_required': True,
            'PPFD_constant': None,
            'PPFD_fillna': None,
            'PPFD_method': 'calculated',
            'PPFD_required': False,
            'P_constant': None,
            'P_fillna': None,
            'P_method': 'input',
            'P_required': True,
            'RH_constant': None,
            'RH_fillna': None,
            'RH_method': 'calculated',
            'RH_required': False,
            'R_constant': None,
            'R_fillna': None,
            'R_method': 'calculated',
            'R_required': False,
            'Rn_constant': None,
            'Rn_fillna': None,
            'Rn_method': 'calculated',
            'Rn_required': False,
            'SWC_constant': None,
            'SWC_fillna': None,
            'SWC_method': 'skip',
            'SWC_required': False,
            'SWP_constant': None,
            'SWP_fillna': None,
            'SWP_method': 'skip',
            'SWP_required': False,
            'Tleaf_C_constant': None,
            'Tleaf_C_fillna': None,
            'Tleaf_C_method': 'skip',
            'Tleaf_C_required': False,
            'Ts_C_constant': None,
            'Ts_C_fillna': None,
            'Ts_C_method': 'input',
            'Ts_C_required': True,
            'Ts_K_constant': None,
            'Ts_K_fillna': None,
            'Ts_K_method': 'skip',
            'Ts_K_required': False,
            'VPD_constant': None,
            'VPD_dd_constant': None,
            'VPD_dd_fillna': None,
            'VPD_dd_method': 'calculated',
            'VPD_dd_required': False,
            'VPD_fillna': None,
            'VPD_method': 'input',
            'VPD_required': True,
            'V_cmax_25_constant': None,
            'V_cmax_25_fillna': None,
            'V_cmax_25_method': 'skip',
            'V_cmax_25_required': False,
            'cloudfrac_constant': None,
            'cloudfrac_fillna': None,
            'cloudfrac_method': 'skip',
            'cloudfrac_required': False,
            'dd_method': 'input',
            'dd_required': True,
            'dom_method': 'skip',
            'eact_constant': None,
            'eact_fillna': None,
            'eact_method': 'calculated',
            'eact_required': False,
            'esat_constant': None,
            'esat_fillna': None,
            'esat_method': 'calculated',
            'esat_required': False,
            'fphen_constant': None,
            'fphen_fillna': None,
            'fphen_method': 'skip',
            'fphen_required': False,
            'h_constant': None,
            'h_fillna': None,
            'h_method': 'skip',
            'h_required': False,
            'hr_method': 'input',
            'hr_required': True,
            'is_daylight_constant': None,
            'is_daylight_fillna': None,
            'is_daylight_method': 'calculated',
            'is_daylight_required': False,
            'leaf_fphen_constant': None,
            'leaf_fphen_fillna': None,
            'leaf_fphen_method': 'skip',
            'leaf_fphen_required': False,
            'mm_method': 'skip',
            'precip_constant': None,
            'precip_fillna': None,
            'precip_method': 'input',
            'precip_required': True,
            'row_index_method': 'calculated',
            'sinB_constant': None,
            'sinB_fillna': None,
            'sinB_method': 'calculated',
            'sinB_required': True,
            'snow_depth_constant': None,
            'snow_depth_fillna': None,
            'snow_depth_method': 'skip',
            'snow_depth_required': False,
            'td_constant': None,
            'td_fillna': None,
            'td_method': 'skip',
            'td_required': False,
            'time_method': 'skip',
            'u__constant': None,
            'u__fillna': None,
            'u__method': 'skip',
            'u__required': False,
            'u_constant': None,
            'u_fillna': None,
            'u_method': 'input',
            'u_required': True,
            'uh_constant': None,
            'uh_fillna': None,
            'uh_method': 'skip',
            'uh_required': False,
            'ustar_constant': None,
            'ustar_fillna': None,
            'ustar_method': 'skip',
            'ustar_ref_constant': None,
            'ustar_ref_fillna': None,
            'ustar_ref_method': 'skip',
            'ustar_ref_required': False,
            'ustar_required': False,
            'year_method': 'skip'
        },
        'sparse_data': False,
        'td_base_temperature': 0,
        'thermal_time_method': 'HOURLY',
        'thermal_time_offset': 0,
        'thermal_time_start': 79
    },
    'VERSION': 11,
    'carbon_allocation': {
        'a_leaf': 18.0,
        'a_root': 18.5,
        'a_stem': 16.0,
        'b_leaf': -18.5,
        'b_root': -20.0,
        'b_stem': -15.0,
        'delta': -0.0507,
        'gamma': 27.3,
        'k': 1.4,
        'lambdav': 0.4,
        'theta': 0.4,
        'use_carbon_allocation': True
    },
    'notes': '',
    'output': {
        'fields': None,
        'log_multilayer': False
    },
    'resistance': {
        'ra_calc_method': 'simple',
        'rext_calc_method': 'const',
        'rsur_calc_method': 'single_layer'
    },
    'soil_moisture': {
        'ASW_FC': 0.12388163529178195,
        'MAD': 0.0,
        'PWP': -4.0,
        'initial_SWC': 0.29,
        'root': 0.75,
        'run_off_fraction': 0.0,
        'soil_config': {
            'FC': 0.29,
            'Ksat': 0.0002286,
            'SWP_AE': -0.00188,
            'b': 6.58
        },
        'soil_texture': 'loam',
        'source': 'P-M'
    }
}
