# -*- coding: utf-8 -*-
# snapshottest: v1 - https://goo.gl/zC4yUc
from __future__ import unicode_literals

from snapshottest import GenericRepr, Snapshot


snapshots = Snapshot()

snapshots['test_all_processes_first_24_hours Process_comments'] = [
    '===== Start of Hourly Processes (Hour: 0) =====',
    'Set Hour',
    'Set data row index',
    '===== Start of Daily Processes =====',
    'set day offset',
    'set day',
    '== Met Processes ==',
    'Calculate the effective temperature',
    'Calculate thermal time from hourly accumulated temperature',
    'Calculate the day length (photoperiod)',
    '== Phenology Processes ==',
    'f_phen supplied (or left at default value of 1.0)',
    'calculate leaf_f_phen_method - disabled',
    'Calculate the phyllochron',
    'Calculate the relative photoperiod',
    'Set plant is sown when dd > sowing_day',
    'Set plant has emerged when td > t_emerge or dd > emerge_day',
    'Get the difference between current td and td at Sowing(Vernalised if on)',
    'Get the difference between current td and td at emergence',
    'Set flag leaf has emerged when td or dd pass flag leaf emergence date',
    'Calculate the emergence rate',
    'Calculate the number of leaf populations that have emerged',
    'Calculate the number of leaf populations that have emerged',
    'Set leaf phenology stages',
    'Calculate the thermal time difference between leaf pop emergence and current td',
    'Get leaf phenology stage for flag leaf',
    'Get phenology stage for plant',
    'Define which populations are growing',
    '== Carbon Allocation Processes ==',
    '== Canopy Structure Processes ==',
    'Use height of primary land cover if height method is constant',
    'Calculate height of top of each layer as a fraction of total canopy height',
    'Get layer height as sum of layer depths below',
    '''Use primary land cover's estimate of total LAI and spread over
                        layers and LCs''',
    'Distribute LAI using constant fractions from config',
    'Calculate the distribution of LAI between land covers',
    'get layer LAI-weighted mean leaf width(Lm_LAI)',
    'Calc_SAI Estimate_total - LAI',
    'Spread single SAI value to layers and LCs',
    'get layer SAI_total',
    'Set leaf lai for single population',
    'Distribute lai between leaf populations',
    'Distribute lai between growing leaf populations using multiplicative method',
    'Convert lai distribution to pop fractions',
    'calculate measured wind canopy displacement parameters',
    '== Soil Moisture Processes ==',
    'Accumulate precipitation',
    'Daily soil water content update from accumulated Penman-Monteith values',
    'P-M - soil moisture calc',
    'reset penman monteith daily accumulators to 0',
    '== Fst Processes ==',
    'Accumulate O3up(fst)',
    'Store the O3up_acc_day from previous day and reset current day to 0.',
    '===== End of Daily Processes =====',
    '=== Met Processes ===',
    'Accumulate daily temperature',
    'Accumulate precipitation',
    'calculate PAR_sun_shade using Farquhar 1997 method',
    'Estimate sunlit LAI fractions',
    'Calculate ustar_ref and monin obukhov length',
    'Set ustar_ref to external input',
    'Calculate ustar_ref using simple method',
    'Calculate estimated windspeed at canopy',
    'Set constant wind speed at each layer',
    'Use air temperature',
    '=== Gsto Setup Processes ===',
    'V_cmax_25 and J_max_25 supplied as constant',
    'Scale v_cmax_25 to layers below canopy',
    'f_VPD method - disabled',
    'f_SWP_method - Disabled',
    'f_O3 method - disabled',
    'Calculate g_bv for photosynthesis',
    '=== Gsto Processes ===',
    'Calculate gsto - multiplicative',
    'Scale mean gsto up to bulk gsto',
    'Scale bulk gsto to canopy gsto',
    'Scale mean gsto up to bulk gsto',
    '=== Ozone Deposition Processes ===',
    'Reset and Calculate the resistance model for O3 over the target canopy',
    'Vd calculation duplicated here just for comparison purposes',
    'Calculate Top Layer Canopy ozone',
    'Calculate Ozone concentration for other layers',
    'Convert O3 ppb to O3 nmol',
    '=== Ozone Dose Processes ===',
    'Reset and setup Leaf Resistance Model',
    'Calculate the O3up (fst) 0_0',
    'Accumulate O3up(fst)',
    'Calculate the Phytotoxic Ozone Dose',
    'Calculate the OT accumulation',
    '=== Soil Moisture Processes ===',
    'Adapt multi-layer O3 resistance model to single-layer H2O resistance',
    'Calculate the total resistance in H2O resistance model',
    'Is soil evaporation blocked?',
    'Calculate PEt RSTO',
    'Hourly Penman-Monteith calculations for evaporation and transpiration',
    '=== Carbon Allocation Processes ===',
    '== Hourly Logging Processes ==',
    'Logging External Values',
    'Logging Values',
    'Copy State',
    'advance_time_step',
    '===== End of Hourly Processes =====',
    '===== Start of Hourly Processes (Hour: 1) =====',
    'Set Hour',
    'Set data row index',
    '=== Met Processes ===',
    'Accumulate daily temperature',
    'Accumulate precipitation',
    'calculate PAR_sun_shade using Farquhar 1997 method',
    'Estimate sunlit LAI fractions',
    'Calculate ustar_ref and monin obukhov length',
    'Set ustar_ref to external input',
    'Calculate ustar_ref using simple method',
    'Calculate estimated windspeed at canopy',
    'Set constant wind speed at each layer',
    'Use air temperature',
    '=== Gsto Setup Processes ===',
    'V_cmax_25 and J_max_25 supplied as constant',
    'Scale v_cmax_25 to layers below canopy',
    'f_VPD method - disabled',
    'f_SWP_method - Disabled',
    'f_O3 method - disabled',
    'Calculate g_bv for photosynthesis',
    '=== Gsto Processes ===',
    'Calculate gsto - multiplicative',
    'Scale mean gsto up to bulk gsto',
    'Scale bulk gsto to canopy gsto',
    'Scale mean gsto up to bulk gsto',
    '=== Ozone Deposition Processes ===',
    'Reset and Calculate the resistance model for O3 over the target canopy',
    'Vd calculation duplicated here just for comparison purposes',
    'Calculate Top Layer Canopy ozone',
    'Calculate Ozone concentration for other layers',
    'Convert O3 ppb to O3 nmol',
    '=== Ozone Dose Processes ===',
    'Reset and setup Leaf Resistance Model',
    'Calculate the O3up (fst) 0_0',
    'Accumulate O3up(fst)',
    'Calculate the Phytotoxic Ozone Dose',
    'Calculate the OT accumulation',
    '=== Soil Moisture Processes ===',
    'Adapt multi-layer O3 resistance model to single-layer H2O resistance',
    'Calculate the total resistance in H2O resistance model',
    'Is soil evaporation blocked?',
    'Calculate PEt RSTO',
    'Hourly Penman-Monteith calculations for evaporation and transpiration',
    '=== Carbon Allocation Processes ===',
    '== Hourly Logging Processes ==',
    'Logging External Values',
    'Logging Values',
    'Copy State',
    'advance_time_step',
    '===== End of Hourly Processes =====',
    '===== Start of Hourly Processes (Hour: 2) =====',
    'Set Hour',
    'Set data row index',
    '=== Met Processes ===',
    'Accumulate daily temperature',
    'Accumulate precipitation',
    'calculate PAR_sun_shade using Farquhar 1997 method',
    'Estimate sunlit LAI fractions',
    'Calculate ustar_ref and monin obukhov length',
    'Set ustar_ref to external input',
    'Calculate ustar_ref using simple method',
    'Calculate estimated windspeed at canopy',
    'Set constant wind speed at each layer',
    'Use air temperature',
    '=== Gsto Setup Processes ===',
    'V_cmax_25 and J_max_25 supplied as constant',
    'Scale v_cmax_25 to layers below canopy',
    'f_VPD method - disabled',
    'f_SWP_method - Disabled',
    'f_O3 method - disabled',
    'Calculate g_bv for photosynthesis',
    '=== Gsto Processes ===',
    'Calculate gsto - multiplicative',
    'Scale mean gsto up to bulk gsto',
    'Scale bulk gsto to canopy gsto',
    'Scale mean gsto up to bulk gsto',
    '=== Ozone Deposition Processes ===',
    'Reset and Calculate the resistance model for O3 over the target canopy',
    'Vd calculation duplicated here just for comparison purposes',
    'Calculate Top Layer Canopy ozone',
    'Calculate Ozone concentration for other layers',
    'Convert O3 ppb to O3 nmol',
    '=== Ozone Dose Processes ===',
    'Reset and setup Leaf Resistance Model',
    'Calculate the O3up (fst) 0_0',
    'Accumulate O3up(fst)',
    'Calculate the Phytotoxic Ozone Dose',
    'Calculate the OT accumulation',
    '=== Soil Moisture Processes ===',
    'Adapt multi-layer O3 resistance model to single-layer H2O resistance',
    'Calculate the total resistance in H2O resistance model',
    'Is soil evaporation blocked?',
    'Calculate PEt RSTO',
    'Hourly Penman-Monteith calculations for evaporation and transpiration',
    '=== Carbon Allocation Processes ===',
    '== Hourly Logging Processes ==',
    'Logging External Values',
    'Logging Values',
    'Copy State',
    'advance_time_step',
    '===== End of Hourly Processes =====',
    '===== Start of Hourly Processes (Hour: 3) =====',
    'Set Hour',
    'Set data row index',
    '=== Met Processes ===',
    'Accumulate daily temperature',
    'Accumulate precipitation',
    'calculate PAR_sun_shade using Farquhar 1997 method',
    'Estimate sunlit LAI fractions',
    'Calculate ustar_ref and monin obukhov length',
    'Set ustar_ref to external input',
    'Calculate ustar_ref using simple method',
    'Calculate estimated windspeed at canopy',
    'Set constant wind speed at each layer',
    'Use air temperature',
    '=== Gsto Setup Processes ===',
    'V_cmax_25 and J_max_25 supplied as constant',
    'Scale v_cmax_25 to layers below canopy',
    'f_VPD method - disabled',
    'f_SWP_method - Disabled',
    'f_O3 method - disabled',
    'Calculate g_bv for photosynthesis',
    '=== Gsto Processes ===',
    'Calculate gsto - multiplicative',
    'Scale mean gsto up to bulk gsto',
    'Scale bulk gsto to canopy gsto',
    'Scale mean gsto up to bulk gsto',
    '=== Ozone Deposition Processes ===',
    'Reset and Calculate the resistance model for O3 over the target canopy',
    'Vd calculation duplicated here just for comparison purposes',
    'Calculate Top Layer Canopy ozone',
    'Calculate Ozone concentration for other layers',
    'Convert O3 ppb to O3 nmol',
    '=== Ozone Dose Processes ===',
    'Reset and setup Leaf Resistance Model',
    'Calculate the O3up (fst) 0_0',
    'Accumulate O3up(fst)',
    'Calculate the Phytotoxic Ozone Dose',
    'Calculate the OT accumulation',
    '=== Soil Moisture Processes ===',
    'Adapt multi-layer O3 resistance model to single-layer H2O resistance',
    'Calculate the total resistance in H2O resistance model',
    'Is soil evaporation blocked?',
    'Calculate PEt RSTO',
    'Hourly Penman-Monteith calculations for evaporation and transpiration',
    '=== Carbon Allocation Processes ===',
    '== Hourly Logging Processes ==',
    'Logging External Values',
    'Logging Values',
    'Copy State',
    'advance_time_step',
    '===== End of Hourly Processes =====',
    '===== Start of Hourly Processes (Hour: 4) =====',
    'Set Hour',
    'Set data row index',
    '=== Met Processes ===',
    'Accumulate daily temperature',
    'Accumulate precipitation',
    'calculate PAR_sun_shade using Farquhar 1997 method',
    'Estimate sunlit LAI fractions',
    'Calculate ustar_ref and monin obukhov length',
    'Set ustar_ref to external input',
    'Calculate ustar_ref using simple method',
    'Calculate estimated windspeed at canopy',
    'Set constant wind speed at each layer',
    'Use air temperature',
    '=== Gsto Setup Processes ===',
    'V_cmax_25 and J_max_25 supplied as constant',
    'Scale v_cmax_25 to layers below canopy',
    'f_VPD method - disabled',
    'f_SWP_method - Disabled',
    'f_O3 method - disabled',
    'Calculate g_bv for photosynthesis',
    '=== Gsto Processes ===',
    'Calculate gsto - multiplicative',
    'Scale mean gsto up to bulk gsto',
    'Scale bulk gsto to canopy gsto',
    'Scale mean gsto up to bulk gsto',
    '=== Ozone Deposition Processes ===',
    'Reset and Calculate the resistance model for O3 over the target canopy',
    'Vd calculation duplicated here just for comparison purposes',
    'Calculate Top Layer Canopy ozone',
    'Calculate Ozone concentration for other layers',
    'Convert O3 ppb to O3 nmol',
    '=== Ozone Dose Processes ===',
    'Reset and setup Leaf Resistance Model',
    'Calculate the O3up (fst) 0_0',
    'Accumulate O3up(fst)',
    'Calculate the Phytotoxic Ozone Dose',
    'Calculate the OT accumulation',
    '=== Soil Moisture Processes ===',
    'Adapt multi-layer O3 resistance model to single-layer H2O resistance',
    'Calculate the total resistance in H2O resistance model',
    'Is soil evaporation blocked?',
    'Calculate PEt RSTO',
    'Hourly Penman-Monteith calculations for evaporation and transpiration',
    '=== Carbon Allocation Processes ===',
    '== Hourly Logging Processes ==',
    'Logging External Values',
    'Logging Values',
    'Copy State',
    'advance_time_step',
    '===== End of Hourly Processes =====',
    '===== Start of Hourly Processes (Hour: 5) =====',
    'Set Hour',
    'Set data row index',
    '=== Met Processes ===',
    'Accumulate daily temperature',
    'Accumulate precipitation',
    'calculate PAR_sun_shade using Farquhar 1997 method',
    'Estimate sunlit LAI fractions',
    'Calculate ustar_ref and monin obukhov length',
    'Set ustar_ref to external input',
    'Calculate ustar_ref using simple method',
    'Calculate estimated windspeed at canopy',
    'Set constant wind speed at each layer',
    'Use air temperature',
    '=== Gsto Setup Processes ===',
    'V_cmax_25 and J_max_25 supplied as constant',
    'Scale v_cmax_25 to layers below canopy',
    'f_VPD method - disabled',
    'f_SWP_method - Disabled',
    'f_O3 method - disabled',
    'Calculate g_bv for photosynthesis',
    '=== Gsto Processes ===',
    'Calculate gsto - multiplicative',
    'Scale mean gsto up to bulk gsto',
    'Scale bulk gsto to canopy gsto',
    'Scale mean gsto up to bulk gsto',
    '=== Ozone Deposition Processes ===',
    'Reset and Calculate the resistance model for O3 over the target canopy',
    'Vd calculation duplicated here just for comparison purposes',
    'Calculate Top Layer Canopy ozone',
    'Calculate Ozone concentration for other layers',
    'Convert O3 ppb to O3 nmol',
    '=== Ozone Dose Processes ===',
    'Reset and setup Leaf Resistance Model',
    'Calculate the O3up (fst) 0_0',
    'Accumulate O3up(fst)',
    'Calculate the Phytotoxic Ozone Dose',
    'Calculate the OT accumulation',
    '=== Soil Moisture Processes ===',
    'Adapt multi-layer O3 resistance model to single-layer H2O resistance',
    'Calculate the total resistance in H2O resistance model',
    'Is soil evaporation blocked?',
    'Calculate PEt RSTO',
    'Hourly Penman-Monteith calculations for evaporation and transpiration',
    '=== Carbon Allocation Processes ===',
    '== Hourly Logging Processes ==',
    'Logging External Values',
    'Logging Values',
    'Copy State',
    'advance_time_step',
    '===== End of Hourly Processes =====',
    '===== Start of Hourly Processes (Hour: 6) =====',
    'Set Hour',
    'Set data row index',
    '=== Met Processes ===',
    'Accumulate daily temperature',
    'Accumulate precipitation',
    'calculate PAR_sun_shade using Farquhar 1997 method',
    'Estimate sunlit LAI fractions',
    'Calculate ustar_ref and monin obukhov length',
    'Set ustar_ref to external input',
    'Calculate ustar_ref using simple method',
    'Calculate estimated windspeed at canopy',
    'Set constant wind speed at each layer',
    'Use air temperature',
    '=== Gsto Setup Processes ===',
    'V_cmax_25 and J_max_25 supplied as constant',
    'Scale v_cmax_25 to layers below canopy',
    'f_VPD method - disabled',
    'f_SWP_method - Disabled',
    'f_O3 method - disabled',
    'Calculate g_bv for photosynthesis',
    '=== Gsto Processes ===',
    'Calculate gsto - multiplicative',
    'Scale mean gsto up to bulk gsto',
    'Scale bulk gsto to canopy gsto',
    'Scale mean gsto up to bulk gsto',
    '=== Ozone Deposition Processes ===',
    'Reset and Calculate the resistance model for O3 over the target canopy',
    'Vd calculation duplicated here just for comparison purposes',
    'Calculate Top Layer Canopy ozone',
    'Calculate Ozone concentration for other layers',
    'Convert O3 ppb to O3 nmol',
    '=== Ozone Dose Processes ===',
    'Reset and setup Leaf Resistance Model',
    'Calculate the O3up (fst) 0_0',
    'Accumulate O3up(fst)',
    'Calculate the Phytotoxic Ozone Dose',
    'Calculate the OT accumulation',
    '=== Soil Moisture Processes ===',
    'Adapt multi-layer O3 resistance model to single-layer H2O resistance',
    'Calculate the total resistance in H2O resistance model',
    'Is soil evaporation blocked?',
    'Calculate PEt RSTO',
    'Hourly Penman-Monteith calculations for evaporation and transpiration',
    '=== Carbon Allocation Processes ===',
    '== Hourly Logging Processes ==',
    'Logging External Values',
    'Logging Values',
    'Copy State',
    'advance_time_step',
    '===== End of Hourly Processes =====',
    '===== Start of Hourly Processes (Hour: 7) =====',
    'Set Hour',
    'Set data row index',
    '=== Met Processes ===',
    'Accumulate daily temperature',
    'Accumulate precipitation',
    'calculate PAR_sun_shade using Farquhar 1997 method',
    'Estimate sunlit LAI fractions',
    'Calculate ustar_ref and monin obukhov length',
    'Set ustar_ref to external input',
    'Calculate ustar_ref using simple method',
    'Calculate estimated windspeed at canopy',
    'Set constant wind speed at each layer',
    'Use air temperature',
    '=== Gsto Setup Processes ===',
    'V_cmax_25 and J_max_25 supplied as constant',
    'Scale v_cmax_25 to layers below canopy',
    'f_VPD method - disabled',
    'f_SWP_method - Disabled',
    'f_O3 method - disabled',
    'Calculate g_bv for photosynthesis',
    '=== Gsto Processes ===',
    'Calculate gsto - multiplicative',
    'Scale mean gsto up to bulk gsto',
    'Scale bulk gsto to canopy gsto',
    'Scale mean gsto up to bulk gsto',
    '=== Ozone Deposition Processes ===',
    'Reset and Calculate the resistance model for O3 over the target canopy',
    'Vd calculation duplicated here just for comparison purposes',
    'Calculate Top Layer Canopy ozone',
    'Calculate Ozone concentration for other layers',
    'Convert O3 ppb to O3 nmol',
    '=== Ozone Dose Processes ===',
    'Reset and setup Leaf Resistance Model',
    'Calculate the O3up (fst) 0_0',
    'Accumulate O3up(fst)',
    'Calculate the Phytotoxic Ozone Dose',
    'Calculate the OT accumulation',
    '=== Soil Moisture Processes ===',
    'Adapt multi-layer O3 resistance model to single-layer H2O resistance',
    'Calculate the total resistance in H2O resistance model',
    'Is soil evaporation blocked?',
    'Calculate PEt RSTO',
    'Hourly Penman-Monteith calculations for evaporation and transpiration',
    '=== Carbon Allocation Processes ===',
    '== Hourly Logging Processes ==',
    'Logging External Values',
    'Logging Values',
    'Copy State',
    'advance_time_step',
    '===== End of Hourly Processes =====',
    '===== Start of Hourly Processes (Hour: 8) =====',
    'Set Hour',
    'Set data row index',
    '=== Met Processes ===',
    'Accumulate daily temperature',
    'Accumulate precipitation',
    'calculate PAR_sun_shade using Farquhar 1997 method',
    'Estimate sunlit LAI fractions',
    'Calculate ustar_ref and monin obukhov length',
    'Set ustar_ref to external input',
    'Calculate ustar_ref using simple method',
    'Calculate estimated windspeed at canopy',
    'Set constant wind speed at each layer',
    'Use air temperature',
    '=== Gsto Setup Processes ===',
    'V_cmax_25 and J_max_25 supplied as constant',
    'Scale v_cmax_25 to layers below canopy',
    'f_VPD method - disabled',
    'f_SWP_method - Disabled',
    'f_O3 method - disabled',
    'Calculate g_bv for photosynthesis',
    '=== Gsto Processes ===',
    'Calculate gsto - multiplicative',
    'Scale mean gsto up to bulk gsto',
    'Scale bulk gsto to canopy gsto',
    'Scale mean gsto up to bulk gsto',
    '=== Ozone Deposition Processes ===',
    'Reset and Calculate the resistance model for O3 over the target canopy',
    'Vd calculation duplicated here just for comparison purposes',
    'Calculate Top Layer Canopy ozone',
    'Calculate Ozone concentration for other layers',
    'Convert O3 ppb to O3 nmol',
    '=== Ozone Dose Processes ===',
    'Reset and setup Leaf Resistance Model',
    'Calculate the O3up (fst) 0_0',
    'Accumulate O3up(fst)',
    'Calculate the Phytotoxic Ozone Dose',
    'Calculate the OT accumulation',
    '=== Soil Moisture Processes ===',
    'Adapt multi-layer O3 resistance model to single-layer H2O resistance',
    'Calculate the total resistance in H2O resistance model',
    'Is soil evaporation blocked?',
    'Calculate PEt RSTO',
    'Hourly Penman-Monteith calculations for evaporation and transpiration',
    '=== Carbon Allocation Processes ===',
    '== Hourly Logging Processes ==',
    'Logging External Values',
    'Logging Values',
    'Copy State',
    'advance_time_step',
    '===== End of Hourly Processes =====',
    '===== Start of Hourly Processes (Hour: 9) =====',
    'Set Hour',
    'Set data row index',
    '=== Met Processes ===',
    'Accumulate daily temperature',
    'Accumulate precipitation',
    'calculate PAR_sun_shade using Farquhar 1997 method',
    'Estimate sunlit LAI fractions',
    'Calculate ustar_ref and monin obukhov length',
    'Set ustar_ref to external input',
    'Calculate ustar_ref using simple method',
    'Calculate estimated windspeed at canopy',
    'Set constant wind speed at each layer',
    'Use air temperature',
    '=== Gsto Setup Processes ===',
    'V_cmax_25 and J_max_25 supplied as constant',
    'Scale v_cmax_25 to layers below canopy',
    'f_VPD method - disabled',
    'f_SWP_method - Disabled',
    'f_O3 method - disabled',
    'Calculate g_bv for photosynthesis',
    '=== Gsto Processes ===',
    'Calculate gsto - multiplicative',
    'Scale mean gsto up to bulk gsto',
    'Scale bulk gsto to canopy gsto',
    'Scale mean gsto up to bulk gsto',
    '=== Ozone Deposition Processes ===',
    'Reset and Calculate the resistance model for O3 over the target canopy',
    'Vd calculation duplicated here just for comparison purposes',
    'Calculate Top Layer Canopy ozone',
    'Calculate Ozone concentration for other layers',
    'Convert O3 ppb to O3 nmol',
    '=== Ozone Dose Processes ===',
    'Reset and setup Leaf Resistance Model',
    'Calculate the O3up (fst) 0_0',
    'Accumulate O3up(fst)',
    'Calculate the Phytotoxic Ozone Dose',
    'Calculate the OT accumulation',
    '=== Soil Moisture Processes ===',
    'Adapt multi-layer O3 resistance model to single-layer H2O resistance',
    'Calculate the total resistance in H2O resistance model',
    'Is soil evaporation blocked?',
    'Calculate PEt RSTO',
    'Hourly Penman-Monteith calculations for evaporation and transpiration',
    '=== Carbon Allocation Processes ===',
    '== Hourly Logging Processes ==',
    'Logging External Values',
    'Logging Values',
    'Copy State',
    'advance_time_step',
    '===== End of Hourly Processes =====',
    '===== Start of Hourly Processes (Hour: 10) =====',
    'Set Hour',
    'Set data row index',
    '=== Met Processes ===',
    'Accumulate daily temperature',
    'Accumulate precipitation',
    'calculate PAR_sun_shade using Farquhar 1997 method',
    'Estimate sunlit LAI fractions',
    'Calculate ustar_ref and monin obukhov length',
    'Set ustar_ref to external input',
    'Calculate ustar_ref using simple method',
    'Calculate estimated windspeed at canopy',
    'Set constant wind speed at each layer',
    'Use air temperature',
    '=== Gsto Setup Processes ===',
    'V_cmax_25 and J_max_25 supplied as constant',
    'Scale v_cmax_25 to layers below canopy',
    'f_VPD method - disabled',
    'f_SWP_method - Disabled',
    'f_O3 method - disabled',
    'Calculate g_bv for photosynthesis',
    '=== Gsto Processes ===',
    'Calculate gsto - multiplicative',
    'Scale mean gsto up to bulk gsto',
    'Scale bulk gsto to canopy gsto',
    'Scale mean gsto up to bulk gsto',
    '=== Ozone Deposition Processes ===',
    'Reset and Calculate the resistance model for O3 over the target canopy',
    'Vd calculation duplicated here just for comparison purposes',
    'Calculate Top Layer Canopy ozone',
    'Calculate Ozone concentration for other layers',
    'Convert O3 ppb to O3 nmol',
    '=== Ozone Dose Processes ===',
    'Reset and setup Leaf Resistance Model',
    'Calculate the O3up (fst) 0_0',
    'Accumulate O3up(fst)',
    'Calculate the Phytotoxic Ozone Dose',
    'Calculate the OT accumulation',
    '=== Soil Moisture Processes ===',
    'Adapt multi-layer O3 resistance model to single-layer H2O resistance',
    'Calculate the total resistance in H2O resistance model',
    'Is soil evaporation blocked?',
    'Calculate PEt RSTO',
    'Hourly Penman-Monteith calculations for evaporation and transpiration',
    '=== Carbon Allocation Processes ===',
    '== Hourly Logging Processes ==',
    'Logging External Values',
    'Logging Values',
    'Copy State',
    'advance_time_step',
    '===== End of Hourly Processes =====',
    '===== Start of Hourly Processes (Hour: 11) =====',
    'Set Hour',
    'Set data row index',
    '=== Met Processes ===',
    'Accumulate daily temperature',
    'Accumulate precipitation',
    'calculate PAR_sun_shade using Farquhar 1997 method',
    'Estimate sunlit LAI fractions',
    'Calculate ustar_ref and monin obukhov length',
    'Set ustar_ref to external input',
    'Calculate ustar_ref using simple method',
    'Calculate estimated windspeed at canopy',
    'Set constant wind speed at each layer',
    'Use air temperature',
    '=== Gsto Setup Processes ===',
    'V_cmax_25 and J_max_25 supplied as constant',
    'Scale v_cmax_25 to layers below canopy',
    'f_VPD method - disabled',
    'f_SWP_method - Disabled',
    'f_O3 method - disabled',
    'Calculate g_bv for photosynthesis',
    '=== Gsto Processes ===',
    'Calculate gsto - multiplicative',
    'Scale mean gsto up to bulk gsto',
    'Scale bulk gsto to canopy gsto',
    'Scale mean gsto up to bulk gsto',
    '=== Ozone Deposition Processes ===',
    'Reset and Calculate the resistance model for O3 over the target canopy',
    'Vd calculation duplicated here just for comparison purposes',
    'Calculate Top Layer Canopy ozone',
    'Calculate Ozone concentration for other layers',
    'Convert O3 ppb to O3 nmol',
    '=== Ozone Dose Processes ===',
    'Reset and setup Leaf Resistance Model',
    'Calculate the O3up (fst) 0_0',
    'Accumulate O3up(fst)',
    'Calculate the Phytotoxic Ozone Dose',
    'Calculate the OT accumulation',
    '=== Soil Moisture Processes ===',
    'Adapt multi-layer O3 resistance model to single-layer H2O resistance',
    'Calculate the total resistance in H2O resistance model',
    'Is soil evaporation blocked?',
    'Calculate PEt RSTO',
    'Hourly Penman-Monteith calculations for evaporation and transpiration',
    '=== Carbon Allocation Processes ===',
    '== Hourly Logging Processes ==',
    'Logging External Values',
    'Logging Values',
    'Copy State',
    'advance_time_step',
    '===== End of Hourly Processes =====',
    '===== Start of Hourly Processes (Hour: 12) =====',
    'Set Hour',
    'Set data row index',
    '=== Met Processes ===',
    'Accumulate daily temperature',
    'Accumulate precipitation',
    'calculate PAR_sun_shade using Farquhar 1997 method',
    'Estimate sunlit LAI fractions',
    'Calculate ustar_ref and monin obukhov length',
    'Set ustar_ref to external input',
    'Calculate ustar_ref using simple method',
    'Calculate estimated windspeed at canopy',
    'Set constant wind speed at each layer',
    'Use air temperature',
    '=== Gsto Setup Processes ===',
    'V_cmax_25 and J_max_25 supplied as constant',
    'Scale v_cmax_25 to layers below canopy',
    'f_VPD method - disabled',
    'f_SWP_method - Disabled',
    'f_O3 method - disabled',
    'Calculate g_bv for photosynthesis',
    '=== Gsto Processes ===',
    'Calculate gsto - multiplicative',
    'Scale mean gsto up to bulk gsto',
    'Scale bulk gsto to canopy gsto',
    'Scale mean gsto up to bulk gsto',
    '=== Ozone Deposition Processes ===',
    'Reset and Calculate the resistance model for O3 over the target canopy',
    'Vd calculation duplicated here just for comparison purposes',
    'Calculate Top Layer Canopy ozone',
    'Calculate Ozone concentration for other layers',
    'Convert O3 ppb to O3 nmol',
    '=== Ozone Dose Processes ===',
    'Reset and setup Leaf Resistance Model',
    'Calculate the O3up (fst) 0_0',
    'Accumulate O3up(fst)',
    'Calculate the Phytotoxic Ozone Dose',
    'Calculate the OT accumulation',
    '=== Soil Moisture Processes ===',
    'Adapt multi-layer O3 resistance model to single-layer H2O resistance',
    'Calculate the total resistance in H2O resistance model',
    'Is soil evaporation blocked?',
    'Calculate PEt RSTO',
    'Hourly Penman-Monteith calculations for evaporation and transpiration',
    '=== Carbon Allocation Processes ===',
    '== Hourly Logging Processes ==',
    'Logging External Values',
    'Logging Values',
    'Copy State',
    'advance_time_step',
    '===== End of Hourly Processes =====',
    '===== Start of Hourly Processes (Hour: 13) =====',
    'Set Hour',
    'Set data row index',
    '=== Met Processes ===',
    'Accumulate daily temperature',
    'Accumulate precipitation',
    'calculate PAR_sun_shade using Farquhar 1997 method',
    'Estimate sunlit LAI fractions',
    'Calculate ustar_ref and monin obukhov length',
    'Set ustar_ref to external input',
    'Calculate ustar_ref using simple method',
    'Calculate estimated windspeed at canopy',
    'Set constant wind speed at each layer',
    'Use air temperature',
    '=== Gsto Setup Processes ===',
    'V_cmax_25 and J_max_25 supplied as constant',
    'Scale v_cmax_25 to layers below canopy',
    'f_VPD method - disabled',
    'f_SWP_method - Disabled',
    'f_O3 method - disabled',
    'Calculate g_bv for photosynthesis',
    '=== Gsto Processes ===',
    'Calculate gsto - multiplicative',
    'Scale mean gsto up to bulk gsto',
    'Scale bulk gsto to canopy gsto',
    'Scale mean gsto up to bulk gsto',
    '=== Ozone Deposition Processes ===',
    'Reset and Calculate the resistance model for O3 over the target canopy',
    'Vd calculation duplicated here just for comparison purposes',
    'Calculate Top Layer Canopy ozone',
    'Calculate Ozone concentration for other layers',
    'Convert O3 ppb to O3 nmol',
    '=== Ozone Dose Processes ===',
    'Reset and setup Leaf Resistance Model',
    'Calculate the O3up (fst) 0_0',
    'Accumulate O3up(fst)',
    'Calculate the Phytotoxic Ozone Dose',
    'Calculate the OT accumulation',
    '=== Soil Moisture Processes ===',
    'Adapt multi-layer O3 resistance model to single-layer H2O resistance',
    'Calculate the total resistance in H2O resistance model',
    'Is soil evaporation blocked?',
    'Calculate PEt RSTO',
    'Hourly Penman-Monteith calculations for evaporation and transpiration',
    '=== Carbon Allocation Processes ===',
    '== Hourly Logging Processes ==',
    'Logging External Values',
    'Logging Values',
    'Copy State',
    'advance_time_step',
    '===== End of Hourly Processes =====',
    '===== Start of Hourly Processes (Hour: 14) =====',
    'Set Hour',
    'Set data row index',
    '=== Met Processes ===',
    'Accumulate daily temperature',
    'Accumulate precipitation',
    'calculate PAR_sun_shade using Farquhar 1997 method',
    'Estimate sunlit LAI fractions',
    'Calculate ustar_ref and monin obukhov length',
    'Set ustar_ref to external input',
    'Calculate ustar_ref using simple method',
    'Calculate estimated windspeed at canopy',
    'Set constant wind speed at each layer',
    'Use air temperature',
    '=== Gsto Setup Processes ===',
    'V_cmax_25 and J_max_25 supplied as constant',
    'Scale v_cmax_25 to layers below canopy',
    'f_VPD method - disabled',
    'f_SWP_method - Disabled',
    'f_O3 method - disabled',
    'Calculate g_bv for photosynthesis',
    '=== Gsto Processes ===',
    'Calculate gsto - multiplicative',
    'Scale mean gsto up to bulk gsto',
    'Scale bulk gsto to canopy gsto',
    'Scale mean gsto up to bulk gsto',
    '=== Ozone Deposition Processes ===',
    'Reset and Calculate the resistance model for O3 over the target canopy',
    'Vd calculation duplicated here just for comparison purposes',
    'Calculate Top Layer Canopy ozone',
    'Calculate Ozone concentration for other layers',
    'Convert O3 ppb to O3 nmol',
    '=== Ozone Dose Processes ===',
    'Reset and setup Leaf Resistance Model',
    'Calculate the O3up (fst) 0_0',
    'Accumulate O3up(fst)',
    'Calculate the Phytotoxic Ozone Dose',
    'Calculate the OT accumulation',
    '=== Soil Moisture Processes ===',
    'Adapt multi-layer O3 resistance model to single-layer H2O resistance',
    'Calculate the total resistance in H2O resistance model',
    'Is soil evaporation blocked?',
    'Calculate PEt RSTO',
    'Hourly Penman-Monteith calculations for evaporation and transpiration',
    '=== Carbon Allocation Processes ===',
    '== Hourly Logging Processes ==',
    'Logging External Values',
    'Logging Values',
    'Copy State',
    'advance_time_step',
    '===== End of Hourly Processes =====',
    '===== Start of Hourly Processes (Hour: 15) =====',
    'Set Hour',
    'Set data row index',
    '=== Met Processes ===',
    'Accumulate daily temperature',
    'Accumulate precipitation',
    'calculate PAR_sun_shade using Farquhar 1997 method',
    'Estimate sunlit LAI fractions',
    'Calculate ustar_ref and monin obukhov length',
    'Set ustar_ref to external input',
    'Calculate ustar_ref using simple method',
    'Calculate estimated windspeed at canopy',
    'Set constant wind speed at each layer',
    'Use air temperature',
    '=== Gsto Setup Processes ===',
    'V_cmax_25 and J_max_25 supplied as constant',
    'Scale v_cmax_25 to layers below canopy',
    'f_VPD method - disabled',
    'f_SWP_method - Disabled',
    'f_O3 method - disabled',
    'Calculate g_bv for photosynthesis',
    '=== Gsto Processes ===',
    'Calculate gsto - multiplicative',
    'Scale mean gsto up to bulk gsto',
    'Scale bulk gsto to canopy gsto',
    'Scale mean gsto up to bulk gsto',
    '=== Ozone Deposition Processes ===',
    'Reset and Calculate the resistance model for O3 over the target canopy',
    'Vd calculation duplicated here just for comparison purposes',
    'Calculate Top Layer Canopy ozone',
    'Calculate Ozone concentration for other layers',
    'Convert O3 ppb to O3 nmol',
    '=== Ozone Dose Processes ===',
    'Reset and setup Leaf Resistance Model',
    'Calculate the O3up (fst) 0_0',
    'Accumulate O3up(fst)',
    'Calculate the Phytotoxic Ozone Dose',
    'Calculate the OT accumulation',
    '=== Soil Moisture Processes ===',
    'Adapt multi-layer O3 resistance model to single-layer H2O resistance',
    'Calculate the total resistance in H2O resistance model',
    'Is soil evaporation blocked?',
    'Calculate PEt RSTO',
    'Hourly Penman-Monteith calculations for evaporation and transpiration',
    '=== Carbon Allocation Processes ===',
    '== Hourly Logging Processes ==',
    'Logging External Values',
    'Logging Values',
    'Copy State',
    'advance_time_step',
    '===== End of Hourly Processes =====',
    '===== Start of Hourly Processes (Hour: 16) =====',
    'Set Hour',
    'Set data row index',
    '=== Met Processes ===',
    'Accumulate daily temperature',
    'Accumulate precipitation',
    'calculate PAR_sun_shade using Farquhar 1997 method',
    'Estimate sunlit LAI fractions',
    'Calculate ustar_ref and monin obukhov length',
    'Set ustar_ref to external input',
    'Calculate ustar_ref using simple method',
    'Calculate estimated windspeed at canopy',
    'Set constant wind speed at each layer',
    'Use air temperature',
    '=== Gsto Setup Processes ===',
    'V_cmax_25 and J_max_25 supplied as constant',
    'Scale v_cmax_25 to layers below canopy',
    'f_VPD method - disabled',
    'f_SWP_method - Disabled',
    'f_O3 method - disabled',
    'Calculate g_bv for photosynthesis',
    '=== Gsto Processes ===',
    'Calculate gsto - multiplicative',
    'Scale mean gsto up to bulk gsto',
    'Scale bulk gsto to canopy gsto',
    'Scale mean gsto up to bulk gsto',
    '=== Ozone Deposition Processes ===',
    'Reset and Calculate the resistance model for O3 over the target canopy',
    'Vd calculation duplicated here just for comparison purposes',
    'Calculate Top Layer Canopy ozone',
    'Calculate Ozone concentration for other layers',
    'Convert O3 ppb to O3 nmol',
    '=== Ozone Dose Processes ===',
    'Reset and setup Leaf Resistance Model',
    'Calculate the O3up (fst) 0_0',
    'Accumulate O3up(fst)',
    'Calculate the Phytotoxic Ozone Dose',
    'Calculate the OT accumulation',
    '=== Soil Moisture Processes ===',
    'Adapt multi-layer O3 resistance model to single-layer H2O resistance',
    'Calculate the total resistance in H2O resistance model',
    'Is soil evaporation blocked?',
    'Calculate PEt RSTO',
    'Hourly Penman-Monteith calculations for evaporation and transpiration',
    '=== Carbon Allocation Processes ===',
    '== Hourly Logging Processes ==',
    'Logging External Values',
    'Logging Values',
    'Copy State',
    'advance_time_step',
    '===== End of Hourly Processes =====',
    '===== Start of Hourly Processes (Hour: 17) =====',
    'Set Hour',
    'Set data row index',
    '=== Met Processes ===',
    'Accumulate daily temperature',
    'Accumulate precipitation',
    'calculate PAR_sun_shade using Farquhar 1997 method',
    'Estimate sunlit LAI fractions',
    'Calculate ustar_ref and monin obukhov length',
    'Set ustar_ref to external input',
    'Calculate ustar_ref using simple method',
    'Calculate estimated windspeed at canopy',
    'Set constant wind speed at each layer',
    'Use air temperature',
    '=== Gsto Setup Processes ===',
    'V_cmax_25 and J_max_25 supplied as constant',
    'Scale v_cmax_25 to layers below canopy',
    'f_VPD method - disabled',
    'f_SWP_method - Disabled',
    'f_O3 method - disabled',
    'Calculate g_bv for photosynthesis',
    '=== Gsto Processes ===',
    'Calculate gsto - multiplicative',
    'Scale mean gsto up to bulk gsto',
    'Scale bulk gsto to canopy gsto',
    'Scale mean gsto up to bulk gsto',
    '=== Ozone Deposition Processes ===',
    'Reset and Calculate the resistance model for O3 over the target canopy',
    'Vd calculation duplicated here just for comparison purposes',
    'Calculate Top Layer Canopy ozone',
    'Calculate Ozone concentration for other layers',
    'Convert O3 ppb to O3 nmol',
    '=== Ozone Dose Processes ===',
    'Reset and setup Leaf Resistance Model',
    'Calculate the O3up (fst) 0_0',
    'Accumulate O3up(fst)',
    'Calculate the Phytotoxic Ozone Dose',
    'Calculate the OT accumulation',
    '=== Soil Moisture Processes ===',
    'Adapt multi-layer O3 resistance model to single-layer H2O resistance',
    'Calculate the total resistance in H2O resistance model',
    'Is soil evaporation blocked?',
    'Calculate PEt RSTO',
    'Hourly Penman-Monteith calculations for evaporation and transpiration',
    '=== Carbon Allocation Processes ===',
    '== Hourly Logging Processes ==',
    'Logging External Values',
    'Logging Values',
    'Copy State',
    'advance_time_step',
    '===== End of Hourly Processes =====',
    '===== Start of Hourly Processes (Hour: 18) =====',
    'Set Hour',
    'Set data row index',
    '=== Met Processes ===',
    'Accumulate daily temperature',
    'Accumulate precipitation',
    'calculate PAR_sun_shade using Farquhar 1997 method',
    'Estimate sunlit LAI fractions',
    'Calculate ustar_ref and monin obukhov length',
    'Set ustar_ref to external input',
    'Calculate ustar_ref using simple method',
    'Calculate estimated windspeed at canopy',
    'Set constant wind speed at each layer',
    'Use air temperature',
    '=== Gsto Setup Processes ===',
    'V_cmax_25 and J_max_25 supplied as constant',
    'Scale v_cmax_25 to layers below canopy',
    'f_VPD method - disabled',
    'f_SWP_method - Disabled',
    'f_O3 method - disabled',
    'Calculate g_bv for photosynthesis',
    '=== Gsto Processes ===',
    'Calculate gsto - multiplicative',
    'Scale mean gsto up to bulk gsto',
    'Scale bulk gsto to canopy gsto',
    'Scale mean gsto up to bulk gsto',
    '=== Ozone Deposition Processes ===',
    'Reset and Calculate the resistance model for O3 over the target canopy',
    'Vd calculation duplicated here just for comparison purposes',
    'Calculate Top Layer Canopy ozone',
    'Calculate Ozone concentration for other layers',
    'Convert O3 ppb to O3 nmol',
    '=== Ozone Dose Processes ===',
    'Reset and setup Leaf Resistance Model',
    'Calculate the O3up (fst) 0_0',
    'Accumulate O3up(fst)',
    'Calculate the Phytotoxic Ozone Dose',
    'Calculate the OT accumulation',
    '=== Soil Moisture Processes ===',
    'Adapt multi-layer O3 resistance model to single-layer H2O resistance',
    'Calculate the total resistance in H2O resistance model',
    'Is soil evaporation blocked?',
    'Calculate PEt RSTO',
    'Hourly Penman-Monteith calculations for evaporation and transpiration',
    '=== Carbon Allocation Processes ===',
    '== Hourly Logging Processes ==',
    'Logging External Values',
    'Logging Values',
    'Copy State',
    'advance_time_step',
    '===== End of Hourly Processes =====',
    '===== Start of Hourly Processes (Hour: 19) =====',
    'Set Hour',
    'Set data row index',
    '=== Met Processes ===',
    'Accumulate daily temperature',
    'Accumulate precipitation',
    'calculate PAR_sun_shade using Farquhar 1997 method',
    'Estimate sunlit LAI fractions',
    'Calculate ustar_ref and monin obukhov length',
    'Set ustar_ref to external input',
    'Calculate ustar_ref using simple method',
    'Calculate estimated windspeed at canopy',
    'Set constant wind speed at each layer',
    'Use air temperature',
    '=== Gsto Setup Processes ===',
    'V_cmax_25 and J_max_25 supplied as constant',
    'Scale v_cmax_25 to layers below canopy',
    'f_VPD method - disabled',
    'f_SWP_method - Disabled',
    'f_O3 method - disabled',
    'Calculate g_bv for photosynthesis',
    '=== Gsto Processes ===',
    'Calculate gsto - multiplicative',
    'Scale mean gsto up to bulk gsto',
    'Scale bulk gsto to canopy gsto',
    'Scale mean gsto up to bulk gsto',
    '=== Ozone Deposition Processes ===',
    'Reset and Calculate the resistance model for O3 over the target canopy',
    'Vd calculation duplicated here just for comparison purposes',
    'Calculate Top Layer Canopy ozone',
    'Calculate Ozone concentration for other layers',
    'Convert O3 ppb to O3 nmol',
    '=== Ozone Dose Processes ===',
    'Reset and setup Leaf Resistance Model',
    'Calculate the O3up (fst) 0_0',
    'Accumulate O3up(fst)',
    'Calculate the Phytotoxic Ozone Dose',
    'Calculate the OT accumulation',
    '=== Soil Moisture Processes ===',
    'Adapt multi-layer O3 resistance model to single-layer H2O resistance',
    'Calculate the total resistance in H2O resistance model',
    'Is soil evaporation blocked?',
    'Calculate PEt RSTO',
    'Hourly Penman-Monteith calculations for evaporation and transpiration',
    '=== Carbon Allocation Processes ===',
    '== Hourly Logging Processes ==',
    'Logging External Values',
    'Logging Values',
    'Copy State',
    'advance_time_step',
    '===== End of Hourly Processes =====',
    '===== Start of Hourly Processes (Hour: 20) =====',
    'Set Hour',
    'Set data row index',
    '=== Met Processes ===',
    'Accumulate daily temperature',
    'Accumulate precipitation',
    'calculate PAR_sun_shade using Farquhar 1997 method',
    'Estimate sunlit LAI fractions',
    'Calculate ustar_ref and monin obukhov length',
    'Set ustar_ref to external input',
    'Calculate ustar_ref using simple method',
    'Calculate estimated windspeed at canopy',
    'Set constant wind speed at each layer',
    'Use air temperature',
    '=== Gsto Setup Processes ===',
    'V_cmax_25 and J_max_25 supplied as constant',
    'Scale v_cmax_25 to layers below canopy',
    'f_VPD method - disabled',
    'f_SWP_method - Disabled',
    'f_O3 method - disabled',
    'Calculate g_bv for photosynthesis',
    '=== Gsto Processes ===',
    'Calculate gsto - multiplicative',
    'Scale mean gsto up to bulk gsto',
    'Scale bulk gsto to canopy gsto',
    'Scale mean gsto up to bulk gsto',
    '=== Ozone Deposition Processes ===',
    'Reset and Calculate the resistance model for O3 over the target canopy',
    'Vd calculation duplicated here just for comparison purposes',
    'Calculate Top Layer Canopy ozone',
    'Calculate Ozone concentration for other layers',
    'Convert O3 ppb to O3 nmol',
    '=== Ozone Dose Processes ===',
    'Reset and setup Leaf Resistance Model',
    'Calculate the O3up (fst) 0_0',
    'Accumulate O3up(fst)',
    'Calculate the Phytotoxic Ozone Dose',
    'Calculate the OT accumulation',
    '=== Soil Moisture Processes ===',
    'Adapt multi-layer O3 resistance model to single-layer H2O resistance',
    'Calculate the total resistance in H2O resistance model',
    'Is soil evaporation blocked?',
    'Calculate PEt RSTO',
    'Hourly Penman-Monteith calculations for evaporation and transpiration',
    '=== Carbon Allocation Processes ===',
    '== Hourly Logging Processes ==',
    'Logging External Values',
    'Logging Values',
    'Copy State',
    'advance_time_step',
    '===== End of Hourly Processes =====',
    '===== Start of Hourly Processes (Hour: 21) =====',
    'Set Hour',
    'Set data row index',
    '=== Met Processes ===',
    'Accumulate daily temperature',
    'Accumulate precipitation',
    'calculate PAR_sun_shade using Farquhar 1997 method',
    'Estimate sunlit LAI fractions',
    'Calculate ustar_ref and monin obukhov length',
    'Set ustar_ref to external input',
    'Calculate ustar_ref using simple method',
    'Calculate estimated windspeed at canopy',
    'Set constant wind speed at each layer',
    'Use air temperature',
    '=== Gsto Setup Processes ===',
    'V_cmax_25 and J_max_25 supplied as constant',
    'Scale v_cmax_25 to layers below canopy',
    'f_VPD method - disabled',
    'f_SWP_method - Disabled',
    'f_O3 method - disabled',
    'Calculate g_bv for photosynthesis',
    '=== Gsto Processes ===',
    'Calculate gsto - multiplicative',
    'Scale mean gsto up to bulk gsto',
    'Scale bulk gsto to canopy gsto',
    'Scale mean gsto up to bulk gsto',
    '=== Ozone Deposition Processes ===',
    'Reset and Calculate the resistance model for O3 over the target canopy',
    'Vd calculation duplicated here just for comparison purposes',
    'Calculate Top Layer Canopy ozone',
    'Calculate Ozone concentration for other layers',
    'Convert O3 ppb to O3 nmol',
    '=== Ozone Dose Processes ===',
    'Reset and setup Leaf Resistance Model',
    'Calculate the O3up (fst) 0_0',
    'Accumulate O3up(fst)',
    'Calculate the Phytotoxic Ozone Dose',
    'Calculate the OT accumulation',
    '=== Soil Moisture Processes ===',
    'Adapt multi-layer O3 resistance model to single-layer H2O resistance',
    'Calculate the total resistance in H2O resistance model',
    'Is soil evaporation blocked?',
    'Calculate PEt RSTO',
    'Hourly Penman-Monteith calculations for evaporation and transpiration',
    '=== Carbon Allocation Processes ===',
    '== Hourly Logging Processes ==',
    'Logging External Values',
    'Logging Values',
    'Copy State',
    'advance_time_step',
    '===== End of Hourly Processes =====',
    '===== Start of Hourly Processes (Hour: 22) =====',
    'Set Hour',
    'Set data row index',
    '=== Met Processes ===',
    'Accumulate daily temperature',
    'Accumulate precipitation',
    'calculate PAR_sun_shade using Farquhar 1997 method',
    'Estimate sunlit LAI fractions',
    'Calculate ustar_ref and monin obukhov length',
    'Set ustar_ref to external input',
    'Calculate ustar_ref using simple method',
    'Calculate estimated windspeed at canopy',
    'Set constant wind speed at each layer',
    'Use air temperature',
    '=== Gsto Setup Processes ===',
    'V_cmax_25 and J_max_25 supplied as constant',
    'Scale v_cmax_25 to layers below canopy',
    'f_VPD method - disabled',
    'f_SWP_method - Disabled',
    'f_O3 method - disabled',
    'Calculate g_bv for photosynthesis',
    '=== Gsto Processes ===',
    'Calculate gsto - multiplicative',
    'Scale mean gsto up to bulk gsto',
    'Scale bulk gsto to canopy gsto',
    'Scale mean gsto up to bulk gsto',
    '=== Ozone Deposition Processes ===',
    'Reset and Calculate the resistance model for O3 over the target canopy',
    'Vd calculation duplicated here just for comparison purposes',
    'Calculate Top Layer Canopy ozone',
    'Calculate Ozone concentration for other layers',
    'Convert O3 ppb to O3 nmol',
    '=== Ozone Dose Processes ===',
    'Reset and setup Leaf Resistance Model',
    'Calculate the O3up (fst) 0_0',
    'Accumulate O3up(fst)',
    'Calculate the Phytotoxic Ozone Dose',
    'Calculate the OT accumulation',
    '=== Soil Moisture Processes ===',
    'Adapt multi-layer O3 resistance model to single-layer H2O resistance',
    'Calculate the total resistance in H2O resistance model',
    'Is soil evaporation blocked?',
    'Calculate PEt RSTO',
    'Hourly Penman-Monteith calculations for evaporation and transpiration',
    '=== Carbon Allocation Processes ===',
    '== Hourly Logging Processes ==',
    'Logging External Values',
    'Logging Values',
    'Copy State',
    'advance_time_step',
    '===== End of Hourly Processes =====',
    '===== Start of Hourly Processes (Hour: 23) =====',
    'Set Hour',
    'Set data row index',
    '=== Met Processes ===',
    'Accumulate daily temperature',
    'Accumulate precipitation',
    'calculate PAR_sun_shade using Farquhar 1997 method',
    'Estimate sunlit LAI fractions',
    'Calculate ustar_ref and monin obukhov length',
    'Set ustar_ref to external input',
    'Calculate ustar_ref using simple method',
    'Calculate estimated windspeed at canopy',
    'Set constant wind speed at each layer',
    'Use air temperature',
    '=== Gsto Setup Processes ===',
    'V_cmax_25 and J_max_25 supplied as constant',
    'Scale v_cmax_25 to layers below canopy',
    'f_VPD method - disabled',
    'f_SWP_method - Disabled',
    'f_O3 method - disabled',
    'Calculate g_bv for photosynthesis',
    '=== Gsto Processes ===',
    'Calculate gsto - multiplicative',
    'Scale mean gsto up to bulk gsto',
    'Scale bulk gsto to canopy gsto',
    'Scale mean gsto up to bulk gsto',
    '=== Ozone Deposition Processes ===',
    'Reset and Calculate the resistance model for O3 over the target canopy',
    'Vd calculation duplicated here just for comparison purposes',
    'Calculate Top Layer Canopy ozone',
    'Calculate Ozone concentration for other layers',
    'Convert O3 ppb to O3 nmol',
    '=== Ozone Dose Processes ===',
    'Reset and setup Leaf Resistance Model',
    'Calculate the O3up (fst) 0_0',
    'Accumulate O3up(fst)',
    'Calculate the Phytotoxic Ozone Dose',
    'Calculate the OT accumulation',
    '=== Soil Moisture Processes ===',
    'Adapt multi-layer O3 resistance model to single-layer H2O resistance',
    'Calculate the total resistance in H2O resistance model',
    'Is soil evaporation blocked?',
    'Calculate PEt RSTO',
    'Hourly Penman-Monteith calculations for evaporation and transpiration',
    '=== Carbon Allocation Processes ===',
    '== Hourly Logging Processes ==',
    'Logging External Values',
    'Logging Values',
    'Copy State',
    'advance_time_step',
    '===== End of Hourly Processes ====='
]
